### ISSUE TITLE
failed to download forests

### ISSUE THREAD

**Issue by aderzelle** [luntergroup/octopus#103]
Hello,

the forests are not downloading when trying to install this way:

octopus version
```
./octopus --version
octopus version 0.7.0 (develop 4e7e5d59)
Target: x86_64 Linux 4.18.0-25-generic
SIMD extension: AVX2
Compiler: GNU 9.2.0
Boost: 1_71

```

```
git clone -b develop https://github.com/luntergroup/octopus.git                                                                                                                                      
octopus/scripts/install.py --install-dependencies --download-forests
```
resulting in forest files not being downloaded, the forests directory is empty. 

```
Downloading https://storage.googleapis.com/luntergroup/octopus/forests/germline.v0.7.0.forest to /mnt/sda1/Alessandro/26-12-2019_testCollapsing/octopus/resources/forests/germline.v0.7.0.forest
Failed to download forest germline.v0.7.0.forest
Downloading https://storage.googleapis.com/luntergroup/octopus/forests/somatic.v0.7.0.forest to /mnt/sda1/Alessandro/26-12-2019_testCollapsing/octopus/resources/forests/somatic.v0.7.0.forest
Failed to download forest somatic.v0.7.0.forest
```

I guess it's a simple question of wrong url.

Thank you!

**Comment by dancooke** [comment]
v0.7.0 is not released yet so the forest files are not available for download. I'm hoping to release v0.7.0 soon (although I've said that for a while now!).

**Comment by DaGaMs** [comment]
Quick follow-up question: will 0.6.3-beta forests work with 0.7.0?

**Comment by dancooke** [comment]
Unfortunately not.

**Comment by jungminchoi** [comment]
@dancooke I am using 0.6.3-beta and wondering if forests would be available for this version. I looked up the google cloud platform but apparently I do not have permissions to download. Thanks!

**Comment by aderzelle** [comment]
Hello,

any news of the forest? As mentioned, it seems impossible to download any forest file from the Google cloud, even previous version. Is it intended? 

Thanks
