### ISSUE TITLE
All forest files unavailable

### ISSUE THREAD

**Issue by aderzelle** [luntergroup/octopus#106]
Hello,

whatever the version, the forest files are unavailable, the Google Cloud sends a message saying we need additional authorisation to download. So even previous version of forest files are unavailable. 
Is it intended? 

Thank you!

**Comment by dancooke** [comment]
Doesn't appear to be any issues; the following works for me

```
wget https://storage.googleapis.com/luntergroup/octopus/forests/germline.v0.6.3-beta.forest
wget https://storage.googleapis.com/luntergroup/octopus/forests/somatic.v0.6.3-beta.forest
```

**Comment by aderzelle** [comment]
Indeed it works with that command! 
if I am write, those forests will not work with the last version of Octopus, only v0.6.3, right?

**Comment by dancooke** [comment]
Correct - they won't work with newer versions.
