### ISSUE TITLE
gVCF?

### ISSUE THREAD

**Issue by aderzelle** [luntergroup/octopus#107]
Hello,

I was wondering if support for the gVCF format was planned? 
I also notice there is no VAF field in the output.
thanks

**Comment by dancooke** [comment]
Reference calling is available for the `individual` calling model. See the [`--refcall`](https://github.com/luntergroup/octopus/wiki/Command-line-reference#option---refcall) command line option.

You might want to checkout the `feature/discontiguous-phasing` branch as this contains some performance improvements related to reference calling - probably this will be merged into `develop` soon.

**Comment by aderzelle** [comment]
Ok thanks, and regarding VAF it field it's a design choice not to have it?

**Comment by dancooke** [comment]
INFO VAF or FORMAT VAF?

**Comment by aderzelle** [comment]
I guess FORMAT, as I mean at the level of my sample

**Comment by dancooke** [comment]
You can use `--annotations VAF` to get VAF annotations during filtering (so long as your filter uses the VAF measure).

**Comment by aderzelle** [comment]
> You can use `--annotations VAF` to get VAF annotations during filtering (so long as your filter uses the VAF measure).

I am not sure to understand how to enforce VAF in the filters as I don't see it in the user manual.
