### ISSUE TITLE
Make forest files more accessible

### ISSUE THREAD

**Issue by tfenne** [luntergroup/octopus#109]
Would it be possible to make the pre-build forest files more accessible please?  If not doing the full install with `scripts/install.py` then it's rather hard to figure out where the forests are and download them.

It would be great if one of the following could be done:
1. Have a mode in `install.py` that _just_ downloads the forest files and isn't dependent on having run the make/cmake build already
2. Make the google bucket/folder where the forest files are publicly listable so it's easy to view in a browser and grab the right files
3. Have up to date links in the readme to the forest files for the last 2-3 version

My tendency has been to install/build octopus semi-manually using the OS's package manager to install dependencies and avoiding homebrew, but then I get stuck trying to guess the right filenames for the forest files and can't tell if I'm guessing wrong or if there isn't a forest file for the version currently on `develop`.  Based on the version in `CMakeLists.txt` I was expecting this path to exist but it does not: `https://storage.googleapis.com/luntergroup/octopus/forests/germline.v0.7.0.forest`.

**Comment by dancooke** [comment]
Hi Tim, I've made the 'octopus' bucket on Google Cloud public. I'll improve the docs with the next release.

**Comment by tfenne** [comment]
Thanks @dancooke !

**Comment by DBS-Max** [comment]
Should I be using the 0.6.3b forest with the current develop branch? Or should I build from the 0.6.3b branch? The 0.7.0 forest files that the develop branch says it downloads aren't actually downloaded.

**Comment by dancooke** [comment]
@DBS-Max The 0.6.3b forests won't work with the develop branch version, and the v0.7.0 forests aren't available yet. So either you can [train your own forest](https://github.com/luntergroup/octopus/wiki/Variant-filtering:-Random-Forest#training-random-forests) with the develop branch version, or just stick with v0.6.3b until v0.7.0 is released.

**Comment by DBS-Max** [comment]
Sounds good, thanks for clarifying.
