### ISSUE TITLE
issue with installation

### ISSUE THREAD

**Issue by skatragadda-nygc** [luntergroup/octopus#115]
Here is my Dockerfile
```
FROM ubuntu:latest

# Get all apt dependencies
RUN apt update
RUN apt install -y software-properties-common
RUN apt update

RUN apt install -y python-dev \
libbz2-dev \
gcc-7 \
libgmp3-dev \
build-essential \
zlib1g-dev \
libncurses5-dev \
libncursesw5-dev \
liblzma-dev \
libhts-dev \
libboost-all-dev \
cmake \
git \
libgmp-dev \
python3 \
wget

RUN wget https://github.com/samtools/htslib/releases/download/1.9/htslib-1.9.tar.bz2 -O htslib.tar.bz2
RUN tar -xjvf htslib.tar.bz2
RUN cd htslib-1.9 && make && make install
RUN cd ..

# Install Octopus
RUN git clone -b master https://github.com/luntergroup/octopus.git
RUN apt install -y curl
RUN octopus/scripts/install.py --install-dependencies --download-forests --threads 4
```

Hello,

We ran into following issues during the installation step while trying to create docker image. Would you know how to resolve this?

build	19-Mar-2020 19:39:14	[ 39%] Building CXX object src/CMakeFiles/octopus.dir/core/callers/cell_caller.cpp.o
build	19-Mar-2020 19:39:33	src/CMakeFiles/octopus.dir/build.make:1574: recipe for target 'src/CMakeFiles/octopus.dir/core/callers/cancer_caller.cpp.o' failed
build	19-Mar-2020 19:39:33	[91mc++: internal compiler error: Killed (program cc1plus)
build	19-Mar-2020 19:39:33	Please submit a full bug report,
build	19-Mar-2020 19:39:33	with preprocessed source if appropriate.
build	19-Mar-2020 19:39:33	See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
build	19-Mar-2020 19:39:33	make[2]: *** [src/CMakeFiles/octopus.dir/core/callers/cancer_caller.cpp.o] Error 4
build	19-Mar-2020 19:39:33	make[2]: *** Waiting for unfinished jobs....
build	19-Mar-2020 19:39:47	[0m[91mmake[1]: *** [src/CMakeFiles/octopus.dir/all] Error 2
build	19-Mar-2020 19:39:47	[0mCMakeFiles/Makefile2:275: recipe for target 'src/CMakeFiles/octopus.dir/all' failed
build	19-Mar-2020 19:39:47	Makefile:129: recipe for target 'all' failed
build	19-Mar-2020 19:39:47	[91mmake: *** [all] Error 2
build	19-Mar-2020 19:40:44	[0mNo bin directory found, making one
build	19-Mar-2020 19:40:44	Installing Octopus 0.6.3-beta (master fd981298)
build	19-Mar-2020 19:40:44	No forest directory found, making one
build	19-Mar-2020 19:40:44	Downloading https://storage.googleapis.com/luntergroup/octopus/forests/germline.v0.6.3-beta.forest to /octopus/resources/forests/germline.v0.6.3-beta.forest
build	19-Mar-2020 19:40:44	Downloading https://storage.googleapis.com/luntergroup/octopus/forests/somatic.v0.6.3-beta.forest to /octopus/resources/forests/somatic.v0.6.3-beta.forest
build	19-Mar-2020 19:40:45	Removing intermediate container ff7a1d3dd769
error	19-Mar-2020 19:40:45	The command '/bin/sh -c octopus/scripts/install.py --install-dependencies --download-forests --threads 4' returned a non-zero code: 2

Thanks in Advance
Sri

**Comment by dancooke** [comment]
Could be that your Docker container ran out of memory. Try building with a single thread (i.e. change `--threads 4` to `--threads 1`), or [increasing memory to the container](https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container).

**Comment by skatragadda-nygc** [comment]
Thanks for your response. We see new error message now

install.py: error: unrecognized arguments: --install-dependencies --download-forests





________________________________
This message is for the recipient’s use only, and may contain confidential, privileged or protected information. Any unauthorized use or dissemination of this communication is prohibited. If you received this message in error, please immediately notify the sender and destroy all copies of this message. The recipient should check this email and any attachments for the presence of viruses, as we accept no liability for any damage caused by any virus transmitted by this email.

**Comment by skatragadda-nygc** [comment]
Changing branch to master from developer this time

________________________________
This message is for the recipient’s use only, and may contain confidential, privileged or protected information. Any unauthorized use or dissemination of this communication is prohibited. If you received this message in error, please immediately notify the sender and destroy all copies of this message. The recipient should check this email and any attachments for the presence of viruses, as we accept no liability for any damage caused by any virus transmitted by this email.

**Comment by skatragadda-nygc** [comment]
It worked this time on a vm with big memory. Thanks for your help!

________________________________
This message is for the recipient’s use only, and may contain confidential, privileged or protected information. Any unauthorized use or dissemination of this communication is prohibited. If you received this message in error, please immediately notify the sender and destroy all copies of this message. The recipient should check this email and any attachments for the presence of viruses, as we accept no liability for any damage caused by any virus transmitted by this email.

**Comment by dancooke** [comment]
No problem.
