### ISSUE TITLE
Source code mentions pacbio css, but means pacbio ccs?

### ISSUE THREAD

**Issue by bredelings** [luntergroup/octopus#117]
Hi,
I was looking through the source code to see if there were any recent commits (since Nov 2019) that might affect my ability to generate usable gvcfs.  Nice C++ code, by the way!  However, I saw pacbio css in a few places, and I wondered if you meant pacbio cCs (i.e. Circular Consensus Sequence).  Not that the compiler cares, of course.
-BenRI

**Comment by dancooke** [comment]
Hi Ben,
Thanks for pointing this out - indeed a typo. Now corrected https://github.com/luntergroup/octopus/commit/84738490e55083a7333b8dab7b6e38dee7bd1194.
Dan
