### ISSUE TITLE
Problem installing on macOS 10.15.3

### ISSUE THREAD

**Issue by nuin** [luntergroup/octopus#126]
**Describe the bug**

I have tried all possible ways to compile on macOS (including some tips from previous issues I've opened) and nothing seems to work.

I tried the develop branch as per install instructions and then release/7.0.0 as it worked before for me on previous versions of macOS and compilers.

**Command**
Command line to install octopus:
```shell
$ ./scripts/install.py
$ ./scripts/install.py --threads 1
$ ./scripts/install.py -c /usr/local/Cellar/llvm/10.0.0_3/bin/clang -cxx /usr/local/Cellar/llvm/10.0.0_3/bin/clang++
```

among others

**Additional context**

`stderr` and `stdout` of the last command run are attached. These files are a little shorted with only three errors. With a regular install with no parameters, I can get up to 30 errors.
[stderr.txt](https://github.com/luntergroup/octopus/files/4730586/stderr.txt)
[stdout.txt](https://github.com/luntergroup/octopus/files/4730587/stdout.txt)

**Comment by dancooke** [comment]
Sorry for the delay. Can you try the latest develop branch?

**Comment by nuin** [comment]
Hi

Compilation seems to work fine with

`./scripts/install.py -c /usr/local/Cellar/llvm/10.0.0_3/bin/clang -cxx /usr/local/Cellar/llvm/10.0.0_3/bin/clang++`

but when trying to execute


```
[100%] Linking CXX executable octopus
[100%] Built target octopus
Install the project...
-- Install configuration: "Release"
-- Installing: /Users/nuin/octopus/bin/octopus
❯ bin/octopus
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicudata.64.dylib
  Referenced from: /usr/local/opt/boost/lib/libboost_log-mt.dylib
  Reason: image not found
[1]    65645 abort      bin/octopus
```

`./scripts/install.py --dependencies -c /usr/local/Cellar/llvm/10.0.0_3/bin/clang -cxx /usr/local/Cellar/llvm/10.0.0_3/bin/clang++`


to make re-install dependencies and make it work properly.
