### ISSUE TITLE
Failed to download forest from google cloud for v0.6.3-beta

### ISSUE THREAD

**Issue by sstadick** [luntergroup/octopus#143]
**Describe the bug**
`wget https://storage.googleapis.com/luntergroup/octopus/forests/germline.v0.6.3-beta.forest` results in 404.

**Version**
v0.6.3-beta

Is this intentional? I see a few other closed issues mentioning this as well.

**Comment by dancooke** [comment]
I removed the v0.6.3-beta forests from Google Cloud as v0.7.0 is released now (with forests). Do you still need the v0.6.3b forests for some reason?

**Comment by sstadick** [comment]
got it! I will go ahead and use v0.7.0. Thanks!
