### ISSUE TITLE
question: use of octopus for mosaic calling

### ISSUE THREAD

**Issue by brentp** [luntergroup/octopus#147]
hi,
we have groups of samples with:
mother, fetus, and 4 placental samples.

we'd like to do a sort of somatic calling to find variants that are absent from mother and fetus but present (likely at very low level) in at least one placental sample. is there an `octopus` calling mode that would be best for this? anywhere specifically I should look in the docs?

thanks,
-Brent

**Comment by dancooke** [comment]
Hi Brent,
Unfortunately none of the existing calling models would really fit this setup. The best you could do at the moment is use the [cancer calling model](https://github.com/luntergroup/octopus/wiki/Calling-models:-Cancer) for the mother and placental samples, where the mother is the normal. That would get you low frequency variants in the placental samples but not in the mother. You can't include the foetus as the cancer calling model assumes all samples have the same germline, so you'd need to look at calling that independently and merging calls, which is obviously not ideal.
Cheers,
Dan

**Comment by brentp** [comment]
Hi Dan,
ok. that makes sense (except the fetus and placental have same DNA, mother is different), I'll give it a try.
thanks for the response and the software.
