### ISSUE TITLE
free() error with cancer calling model

### ISSUE THREAD

**Issue by jbedo** [luntergroup/octopus#150]
**Describe the bug**

Calling commences but after some progress octopus terminates with an `free()` error (see [log](https://github.com/luntergroup/octopus/files/6126165/octopus.txt)). Seems to be pretty common, happens on ~10% of our cohort. The entire cohort called fine with 0.7.0.

**Version**
0.7.1

```shell
octopus version 0.7.1
Target: x86_64 Linux 3.10.0-957.el7.x86_64
SIMD extension: AVX2
Compiler: GNU 9.3.0
Boost: 1_69
```

**Command**
Command line to install octopus:
```shell
$ nix build nixpkgs#octopus-caller
```

Command line to run octopus:
```shell
$ octopus -R ref.fa -I *.bam -o $out \\
  --bamout $evidence \\
  --threads=$NIX_BUILD_CORES \\
  --fast \\
  --max-genotypes 1000 \\
  -T chr22 \\
  -N $normal \\
  --annotations AF
```

**Additional context**
Add any other context about the problem here, e.g.

 - Reference [e.g. hg19]. Please provide link to fasta if atypical.
 grch38

 - BAM files (if possible).
Unfortunately not, it's patient data.

**Comment by dancooke** [comment]
Thanks. I've already encountered this one myself and have started working on a fix.

**Comment by jbedo** [comment]
Thanks for your efforts! Let me know if you need me to test a patch.

**Comment by dancooke** [comment]
Please can you try cf636091cf9b022a6ed13bc0add4e76b9176f4bd?

**Comment by jbedo** [comment]
Testing now, I'm unfortunatly stuck in our computing queue waiting for
an allocation. Hopefully won't be too long.

**Comment by jbedo** [comment]
The specific issue appears to be resolved, though I now seem to have a hanging issue where it gets stuck waiting for a futex. If I can get more details I'll open a separate issue for that.

**Comment by dancooke** [comment]
Ok - I'm no longer seeing this issue in my runs either so I'll close. Please do open another issue for the hanging problem.

**Comment by lordkev** [comment]
I'm hitting the hanging waiting for a futex also. Will see if I can find a way to replicate it and open a new issue.
