### ISSUE TITLE
0.70/0.71 on conda

### ISSUE THREAD

**Issue by jdm204** [luntergroup/octopus#151]
Hi, thanks for your work on octopus, it's great!

I was wondering if the 0.7* series will be available on conda/bioconda?

 I saw issue #139, but `conda search` or browsing the bioconda [website](https://bioconda.github.io/recipes/octopus/README.html) only lists up to 0.6.3b-3 and the linked meta.yaml has a hardcoded version:  `url: https://github.com/luntergroup/{{ name }}/archive/v0.6.3-beta.tar.gz`.

**Comment by dancooke** [comment]
Hi, I've made a [pull request](https://github.com/bioconda/bioconda-recipes/pull/27169) for an updated Conda version but I'm having problems with the build process (old GCC being used).

**Comment by jdm204** [comment]
Ah my bad, thanks!

**Comment by ptranvan** [comment]
any news about this ?

**Comment by dancooke** [comment]
Still trying - it's slow going as the CI build won't work due to memory restrictions.

**Comment by dancooke** [comment]
v0.7.4 is now available on Bioconda for Linux.
