### ISSUE TITLE
Option to call a set of know variants in cancer model in addition to classic calling?

### ISSUE THREAD

**Issue by alxsimon** [luntergroup/octopus#155]
Hi, this is a usage question about the cancer model calling.

I have just started looking at octopus and wondered if it could apply to my use case: tumour only calling in a non-model organism.
I need to call both somatic variants and a set of known germline variants from the population.
I did not see in the documentation if there was a way to call both at the same time.

This would maybe be the equivalent in Freebayes of:
```
-@ --variant-input VCF                                                        
                Use variants reported in VCF file as input to the algorithm.  
                Variants in this file will included in the output even if     
                there is not enough support in the data to pass input filters.
```

Or in GATK Mutect2 a combination of `--panel-of-normals` and `--genotype-pon-sites`.

I don't think the planned option `--regenotype` would fit this need, as this would not look for unknown somatic or germline variants.

Thanks

**Comment by dancooke** [comment]
Hi, Octopus will automatically call both germline and somatic variants in cancer mode. Have you seen the [wiki](https://github.com/luntergroup/octopus/wiki/Calling-models:-Cancer) documentation, in particular the [section on VCF output](https://github.com/luntergroup/octopus/wiki/Calling-models:-Cancer#vcf-output)?

For tumour-only calling there will be a high degree of uncertainty in germline/somatic classification for some variants, so make sure to look at the `PP` INFO field.

In terms of supplying known variants, you can do this with the [`--source-candidates`](https://github.com/luntergroup/octopus/wiki/Command-line-reference#option---source-candidates) option, but this doesn't guarantee the sites will appear in the output and doesn't act like a panel of normals either.

**Comment by alxsimon** [comment]
Thanks for the links, I see what you mean.

I think my question was not clear on one detail, and correct me if I am wrong.
Imagine a position that is not variable in the sample considered (all reads have the same allele), I imagine this would not appear in the output.
I may need to output such informative variants (for example I know fixed between two species or two population) for latter analyses.

Honestly this is just a detail, as I think I would be able to retrieve this information with either another tool (or maybe the individual calling model), this would just avoid two pass on the whole bam.

**Comment by dancooke** [comment]
If I understand correctly, you want to be able to call homozygous reference genotypes at particular sites? Unfortunately, the cancer calling model doesn't support this yet. There's limited support for reference calling (i.e., so called "gVCFs") in the individual calling model (see the [`--refcall`](https://github.com/luntergroup/octopus/wiki/Command-line-reference#option---refcall) option), but it's untested and can result in poor runtime/memory performance in some cases. I'm hoping to work more on this at some point.

**Comment by alxsimon** [comment]
Yes, both homozygous ref and alt alleles at a set of given sites.
That's fine anyway, as I said this is an edge case and I will find a workaround.
I just wanted to be sure this was not possible before going another way for this.
Thanks for the quick answers!
