### ISSUE TITLE
PS type String in VCF header (0.7.2_develop_7ce50979)

### ISSUE THREAD

**Issue by jdm204** [luntergroup/octopus#161]
**Describe the bug**
Running octopus built from source locally (as described in this issue) but also from docker, Octopus outputs a VCF header with `##FORMAT=<ID=PS,Number=1,Type=String,Description="Phase set">`, i.e with PS as a String, but in the source (`vcf_header.cpp`) it looks like it should be an integer: `result.add_format("PS", "1", "Integer", "Phase set");`.

I originally saw this when running octopus via docker in snakemake, and built octopus from the 0.7.2 Github release (though this has 0.7.1 as version in the CMakeLists.txt) as well as current develop, but I still see "String" not "Integer".

**Version**

```shell
$ octopus --version
octopus version 0.7.2 (develop 7ce50979)
Target: x86_64 Linux 5.8.0-48-generic
SIMD extension: AVX512
Compiler: GNU 10.2.0
Boost: 1_75
```

**Command**
Command line to install octopus:
```shell
$ git clone -b develop https://github.com/luntergroup/octopus.git
$ cd octopus
$ scripts/install.py --dependencies --forests -cxx g++-10 -c gcc-10 --threads 6
```

Command line to run octopus:
```shell
$ octopus -R ref.fasta -I bam/out.bam -o octopus.vcf -C polyclone --bamout octopus_bamout.bam --threads 5
```

**Comment by dancooke** [comment]
Thanks. Should be resolved in a97cba89b85c975efa5f2e0c0cea4cc0c2f29560.
