### ISSUE TITLE
Failed to download forest files

### ISSUE THREAD

**Issue by satzel** [luntergroup/octopus#167]
**Describe the bug**
When trying to run ./scripts/install.py --forests to download the respective forest files it fails. Looking at it it seems like the googlebucket contains v.0.7.2 but the script calls for 0.7.1?

**Version**

```shell
$ octopus --version
octopus version 0.7.1
Target: x86_64 Linux 3.10.0-1127.18.2.el7.x86_64
SIMD extension: AVX512
Compiler: GNU 10.2.0
Boost: 1_74

``
This is the output:

Install the project...
-- Install configuration: "Release"
-- Installing: /tmp/octopus-0.7.1/bin/octopus
No forest directory found, making one
Downloading https://storage.googleapis.com/luntergroup/octopus/forests/germline.v0.7.1.forest.gz to /tmp/octopus-0.7.1/resources/forests/germline.v0.7.1.forest.gz
Failed to download forest germline.v0.7.1.forest.gz
Downloading https://storage.googleapis.com/luntergroup/octopus/forests/somatic.v0.7.1.forest.gz to /tmp/octopus-0.7.1/resources/forests/somatic.v0.7.1.forest.gz
Failed to download forest somatic.v0.7.1.forest.gz

**Comment by satzel** [comment]
I assume I should just get octopus version 0.7.2 to solve this...

**Comment by satzel** [comment]
updated to 0.7.2 and gonna close this, cheers

**Comment by dancooke** [comment]
> When trying to run ./scripts/install.py --forests to download the respective forest files it fails. Looking at it it seems like the googlebucket contains v.0.7.2 but the script calls for 0.7.1?

Thanks - yes this is because I accidentally forgot to bump the version number in the source code for the v0.7.2 release.
