### ISSUE TITLE
Encountered an unknown error during calling. 

### ISSUE THREAD

**Issue by gamzemdn** [luntergroup/octopus#168]
Hi! 
I am using the same files as I use with Mutect2 and Varscan. I had no trouble with them but for comparative analysis I ran octopus with same normal-tumor pair using Random Forest option and got the error in the title. I tried different command lines and solutions in the issues but still no luck. Can you help me resolve this?
My NORMAL file has SRA code of SRR3182484 and my tumor file has SRR3182485

P.S. I tried without Random forest option and got the same error
Thank you

**Version**
octopus 0.5.2-beta

MY command line is
octopus -R '/Homo_sapiens/UCSC/hg38/Sequence/WholeGenomeFasta/genome.fa' \
-I normal.bam tumor1recalibratedoutput.bam -N normal \
--somatics-only \
--somatic-forest '/home/gamze/Downloads/octopus_forests_somatic.v0.7.2.forest' \
-o octopus_somatic.vcf.gz \
--debug

I am providing screenshots of cmd as well and log file since it is big.
![Screenshot from 2021-04-15 00-25-18](https://user-images.githubusercontent.com/81433698/114783769-e4828380-9d82-11eb-882d-377235bacc58.png)
![Screenshot from 2021-04-15 00-25-20](https://user-images.githubusercontent.com/81433698/114783781-e77d7400-9d82-11eb-9988-ebe781770518.png)
![Screenshot from 2021-04-15 00-38-45](https://user-images.githubusercontent.com/81433698/114783824-f532f980-9d82-11eb-929e-508972940eaa.png)

**Comment by dancooke** [comment]
Hi, thanks for the bug report. Just to confirm you're using v0.5.2b? This is **really** old. Can you try a newer version?

**Comment by maden21** [comment]
Hi! 

I got the following error when trying to install latest version


![Screenshot from 2021-04-17 16-15-14](https://user-images.githubusercontent.com/81433698/115114452-246e8400-9f98-11eb-9813-88d48bf178e2.png)

**Comment by maden21** [comment]
Hi I upgraded to v0.6.3b and ran the same command line. This time I got the error below in the log file 

Thanks 

![Screenshot from 2021-04-17 19-14-03](https://user-images.githubusercontent.com/81433698/115119474-2abd2a00-9fb1-11eb-9bef-616bcfad56c3.png)

**Comment by maden21** [comment]
providing the cmd file as well
![Screenshot from 2021-04-17 19-46-41](https://user-images.githubusercontent.com/81433698/115120345-aa4cf800-9fb5-11eb-89b9-ee0547eb36b1.png)

**Comment by dancooke** [comment]
Sorry for the delay in replying to this - v0.6.3b is still old. Please can you try the latest version (v0.7.4). This Bioconda package has just been updated to this version if that's how your installing Octopus.

**Comment by gamzemdn** [comment]
Hey Dan!

Sorry for the late feedback. Updating resolved the issue, thank you for the guidance, I think we can close the issue now :)

Best wishes,
