### ISSUE TITLE
[Error] memory corruption

### ISSUE THREAD

**Issue by Sparkle-27** [luntergroup/octopus#171]
Hello，
when I run the following command, error occur in the picture. Do you have any suggestion? Thanks in advance.
 octopus -R reference -I H10.markdup.bam -o H10.vcf
![QQ截图20210418223924](https://user-images.githubusercontent.com/21327136/115167261-7a9f0c80-a0e9-11eb-9a94-9a368f2f15ee.png)

**Comment by dancooke** [comment]
You're using v0.4.1-**alpha** which is over 2 years olds. Please update to a newer version.
