### ISSUE TITLE
variant position in repeats

### ISSUE THREAD

**Issue by cariaso** [luntergroup/octopus#172]
https://github.com/KarchinLab/open-cravat/issues/64
is a specific real world case of a variant within a TG repeat, where the lack of standard positioning across all tools and databases seems to cause a problem. 

Does octopus enforce some policy on correct positioning? (5'? 3'? best effort or guaranteed?)
What are your views on the ability and desirability of standardization across different tools?

**Comment by dancooke** [comment]
Octopus left aligns variants as described [here](https://genome.sph.umich.edu/wiki/Variant_Normalization). You can consider this a guarantee - if you find instances where variants are not left aligned then I'm happy to consider it a bug.

**Comment by cariaso** [comment]
thanks for the confirmation.
