### ISSUE TITLE
Variants in which the reference allele has a very low allele fraction are marked for filtering in the cancer model

### ISSUE THREAD

**Issue by TBradley27** [luntergroup/octopus#173]
**Describe the bug**
Variants in which the reference allele has a very low allele fraction are marked for filtering by the AF filter

**Version**

```shell
$ octopus --version
octopus version 0.7.2 (728bdb81)
Target: x86_64 Linux 3.10.0-1127.18.2.el7.x86_64
SIMD extension: AVX2
Compiler: GNU 9.3.0
Boost: 1_75
```

**Command**
Command line to install octopus:
```shell
$  octopus/scripts/install.py --dependencies --forests
```

Command line to run octopus:
```shell
'octopus \
                                -C cancer \
                                --allow-marked-duplicates \
                                --allow-octopus-duplicates \
                                --min-expected-somatic-frequency 0.05 \
                                --min-credible-somatic-frequency 0.01 \
                                --max-somatic-haplotypes 2 \
                                --filter-expression "QUAL < 10 | MQ < 10 | MP < 10 | AD < 1 | AF < 0.01 | AFB > 0.95 | SB > 0.98 | BQ < 15 | DP < 1 | ADP < 1" \
                                --somatic-filter-expression "QUAL < 2 | GQ < 20 | MQ < 30 | SMQ < 40 | SB > 0.90 | SD > 0.90 | BQ < 20 | DP < 3 | ADP < 1 | MF > 0.2 | NC > 1 | FRF > 0.5 | AD < 1 | AF < 0.0001" \
                                --annotations SB SD AF \
                                --threads \
                                -w temp/ \
                                -I {input.tumour_bams} \
                                --regions-file {input.interval_file} \
                                --output {output.tumour_vcf} \
                                -R {input.reference_genome}'
```

**Additional context**
Add any other context about the problem here, e.g.

 - Reference: GRCh37_g1kp2 (i.e. version of GRCh37 developed/released for use in the 1000 genomes project)
 - Sequencing data: Illumina amplicon sequencing data. 150bp paired-end

Hello,

I am not sure if this is intended behaviour or not, but octopus seems to be labelling variants in which the reference allele has a very low allele fraction for filtering by the AF filter. For example:

![image](https://user-images.githubusercontent.com/13511784/116220729-d8b09d00-a744-11eb-8f5f-17a8432dd52e.png)

Apologies in advance if I have misunderstood the intended behaviour of the tool. I have not tested this on other calling models.

Thanks!

**Comment by dancooke** [comment]
This is currently expected behaviour - for all threshold conditions applied to multi-value annotations the filter is applied to all values.

**Comment by TBradley27** [comment]
Hello again,

Apologies for necroposting but I thought I would flag this issue up as there are one or two more findings from my end

The issue that I am running into at the moment is that octopus is not capturing some loss of heterozygosity events. This is a common event for key cancer-linked genes such as BRCA1 and BRCA2. In these instances, the normal sample is heterozygous at a given locus. Copy number aberrations once cells become cancerous can cause loss of the wild type allele. This can lead to very high MAFs/VAFs for the mutant allele for high purity tumour samples.

Octopus correctly identifies these types of variants as germline - but sometimes filters these variants due to the AF filter or the AFB filter. But if I understand correctly - the genotyping model does not account for loss of germline haplotypes? And assumes a copy number of two for germline haplotypes?

I was wondering if that any parameterisation can be done to capture (i.e. not filter/remove) these events from variant calling?
