### ISSUE TITLE
Cohort of low coverage unmatched somatic exome data

### ISSUE THREAD

**Issue by njbernstein** [luntergroup/octopus#174]
Hi there, 

For a cohort of unmatched somatic data should all samples be included in the same invocation of like so:
`octopus -R hs37d5.fa -I tumourA.bam tumourB.bam -C cancer` where `tumourA.bam` and `tumourB.bam` are from separate individuals but with the same tissue. Does this allow `octopus` to identify common sequencing artifacts which you might find via a panel of normals?

or does the cancer functionality of octopus only operate on a single patient's samples at the same time?

**Comment by dancooke** [comment]
As stated in the [docs](https://github.com/luntergroup/octopus/wiki/Calling-models:-Cancer), the cancer model assumes samples are from the same individual. Octopus does not support panel of normals.

**Comment by njbernstein** [comment]
Sounds good. Thanks!
