### ISSUE TITLE
Fail to run octopus 0.7.4 on two different HCC installed from anaconda 

### ISSUE THREAD

**Issue by margrzy7** [luntergroup/octopus#180]
**Describe the bug**
Hi, I have installed octopus (0.7.4) with conda:
`conda install -c bioconda octopus=0.7.4`

on two different HCC (AMD Interlagos (6272 / 6376); Xeon E5-2670) and in both cases after executing octopus I have gotten following error:
`Illegal instruction`
 
On HCC with Xeon I was able to build octopus from source. 

Do you have any suggestion how I can fix this problem? 

Best,
Marcin

**Comment by dancooke** [comment]
Hi, the Bioconda package is built to a Haswell architecture - the minimum required for AVX2. I'm not keen to go to an older architecture as performance is substantially worse without AVX2 and I think most HPCs should now support that - I may reconsider if enough people report this problem. For now, your only option is to build from source. If you want to stick with Conda then you can use `conda build` - you'll need to edit the `--architecture` option in the [build command](https://github.com/bioconda/bioconda-recipes/blob/master/recipes/octopus/build.sh). Note that if you want to run on both your AMD and Intel compute nodes with the same binary then you'll need to compile to a generic x86 architecture with SSE2. Probably the easier and better option would be to build separate binaries for the two machines - if you just run the build command on the host machine then you can omit the `--architecture` option as the default is `--architecture=native`.

**Comment by brentp** [comment]
Hi, in case anyone else gets here, I also had this problem on multiple installs of octopus on our HPC. When I ran an interactive node with 8G of memory, simply running `octopus` without any args would result in `Illegal instruction` . When I ran with 18GB it works fine. (The recent conda build supports sandybridge).

**Comment by IdoBar** [comment]
Hi @dancooke ,

I'm having the same issue...
For some reason, octopus (installed via `bioconda`) runs well on the login node of our institute's HPC, but fails with the `Illegal instruction` on the compute nodes.
In addition, I noticed that the conda installation is missing the `distro` and `seaborn` packages for the `profiler.py` script to work (and I think the script should be made available as an executable in the conda environment).

Thanks, Ido

**Comment by ESDeutekom** [comment]
Same issue. Is there a docker image on the docker site? It would work better (easier) with our pipeline integration this way....
