### ISSUE TITLE
Merging VCFs v4.3

### ISSUE THREAD

**Issue by tahashmi** [luntergroup/octopus#188]
Hi,

Is there a tool available or `octopus` has some option to merge multiple VCF files produced by `octopus` for different regions?
As `Picard` vcfmerge option doesn't support `VCFv4.3` nor vcftools/bcftools have support for `VCFv4.3`.

Thanks!

**Comment by dancooke** [comment]
bcftools does support VCF v4.3 merging. You can also use RTG Tools vcfmerge.
