### ISSUE TITLE
conda installation

### ISSUE THREAD

**Issue by KamilSJaron** [luntergroup/octopus#189]
Hi there, I somehow run in exactly the same problem as described in #27 #34 #39 and presumably resolved in the [conda issue](https://github.com/bioconda/bioconda-recipes/issues/11790). 

    octopus -v
    Illegal instruction (core dumped)

I tried to install it using `conda install -c conda-forge -c bioconda octopus` in a fresh conda environment (a bit older 4.7.12) running on Debian GNU/Linux 9 (stretch).

The version of octopus that was installed was

    octopus            bioconda/linux-64::octopus-0.7.4-h40a150c_0
    
I am not sure what went wrong and not even where to start with debugging

**Comment by dancooke** [comment]
Hey, I think you're probably running into the same issue as #180 (see my [comment](https://github.com/luntergroup/octopus/issues/180#issuecomment-843069278)).

**Comment by KamilSJaron** [comment]
Yep, that's going to be the problem. I will probs build it from the source then. Thanks!
