### ISSUE TITLE
Q: Tumor only variant calling

### ISSUE THREAD

**Issue by kokyriakidis** [luntergroup/octopus#192]
Hi!

Do you have any recent benchmarks regarding Tumor only variant calling (vs Mutect)?

Thanks,
Konstantinos

**Comment by dancooke** [comment]
Hi, we presented some tumour-only benchmarks in the [Nature Biotechnology paper](https://www.nature.com/articles/s41587-021-00861-3). We don't compare to Mutect2 as this tool [doesn't officially support tumour-only calling](https://gatk.broadinstitute.org/hc/en-us/articles/360035531132) - it doesn't try to classify germline and somatic variants.
