### ISSUE TITLE
Vcf format

### ISSUE THREAD

**Issue by gmykim** [luntergroup/octopus#194]
I'm wondering if I could get a clarification on the vcf output format. I need the SVTYPE (specifically deletion) and the End positions that correspond to the start position (thus giving me the length of the SV). 

Thanks in advance!

**Comment by dancooke** [comment]
Octopus doesn't report symbolic SV variants - all variants are reported as "SNPs and small indels" (section 5.2 of [VCF 4.3 spec](https://samtools.github.io/hts-specs/VCFv4.3.pdf)).
