### ISSUE TITLE
Q: Work for long reads data?

### ISSUE THREAD

**Issue by zhengzhenxian** [luntergroup/octopus#196]
Hi, 
   Thanks for your great work, I am interesting that is octopus possible to work in PacBio HiFi or ONT long reads sequencing data? Or any suggestions if wanna transfer to long reads data? 

Thanks!

**Comment by zhengzhenxian** [comment]
Hi,
   To clarify more, I am only referring to using octopus for somatic variant calling using long reads data. 

Thanks!

**Comment by dancooke** [comment]
Hi, long-reads are not officially supported yet. You can try the latest develop branch and the bundled [PacBio CCS config](https://github.com/luntergroup/octopus/commit/1bba140ec68ac211e50f251ff640a8f0c48ee535).

**Comment by zhengzhenxian** [comment]
Thanks! I might have a try on the config setting.

**Comment by jelber2** [comment]
Just a comment that at least at the moment, I had to comment out 

    #max-region-to-assemble=1000
    #max-assemble-region-overlap=500
    and 
    #disable-early-phase-detection=true

  in https://github.com/luntergroup/octopus/blob/2f91f5ed307d8ee659641a8232a41da6767fd841/resources/configs/PacBioCCS.config

based on using octopus 2f91f5e with PacBio CCS reads
