### ISSUE TITLE
Adding a version tag of the Docker Image on DockerHub

### ISSUE THREAD

**Issue by tinyheero** [luntergroup/octopus#201]
Thanks for putting a Docker image on Dockerhub! I am assuming that the official repository is at https://hub.docker.com/r/dancooke/octopus. Would it be possible to add a version tag (e.g. 0.7.4) in addition to the latest tag? This would make reproducibility easier as I can always reference a specific version tag when pulling. For instance:

```bash
docker pull dancooke/octopus:0.7.4
```

While `docker pull dancooke/octopus` works, it will always pull the latest which presumbly will eventually be a newer release that could break existing code (e.g. downloading a newer version when the code has been setup for an older version)

Kind regards,

**Comment by dancooke** [comment]
[Done](https://hub.docker.com/layers/160576394/dancooke/octopus/0.7.4/images/sha256-10298d0c50266eed6116fb6ad0c31ff30ced0af500ea0936c1934eeee277a799?context=repo)

**Comment by tinyheero** [comment]
Thank you!
