### ISSUE TITLE
Installation error: moving a local object in a return statement prevents copy elision

### ISSUE THREAD

**Issue by svm-zhang** [luntergroup/octopus#208]
**Describe the bug**
Try to build octopus in docker without building local dependencies. The error happen with building the `cancer_caller.cpp.o`. Please see the error message in the attached [snapshot.]()
![octopus_build_error](https://user-images.githubusercontent.com/3883886/133665435-eb45ef04-b7e9-4db4-9d4a-50e942c455f6.png).

Please let me know how I can fix this. Thank you in advance.

Simo

**Version**

```shell
$ octopus --version
v0.7.4

$ gcc -v
9.3.0

```
Boost=1.70
cmake=3.18.2
htslib=1.13
python=3.8.8

**Command**
Command line to install octopus:
```shell
$ ./install.py --forests --threads 1
```

Command line to run octopus:
```shell
$ NA
```

**Additional context**
Add any other context about the problem here, e.g.

 - Reference [e.g. hg19]. Please provide link to fasta if atypical.
 - BAM files (if possible).

**Comment by dancooke** [comment]
Can you provide the full output from the `install.py` command (and please copy and paste rather than posting a screen shot)?
