### ISSUE TITLE
question: trio mode for larger families

### ISSUE THREAD

**Issue by brentp** [luntergroup/octopus#209]
Hi Daniel, given a quad, would octopus perform the trio calling for each trio with, e.g.:

```
$ octopus -R $ref -I bro.bam sis.bam dad.bam mom.bam -M mom -F dad
```
? Or should I send that as two separate `octopus` runs, once for each trio?
thanks for the great software!

**Comment by dancooke** [comment]
Hi Brent, unfortunately quad's are not supported by the [trio](https://luntergroup.github.io/octopus/docs/guides/models/trio/) model. Your options are:

- Use the [population](https://luntergroup.github.io/octopus/docs/guides/models/population) model. This won't give you labelled `DENOVO` calls.
- Run the trio model twice (as you suggested).
- Try the experimental [family](https://github.com/luntergroup/octopus/tree/feature/family) model that handles general pedigrees - you'll need to specify the [`--pedigree`](https://luntergroup.github.io/octopus/docs/cli#--pedigree) option.

**Comment by brentp** [comment]
Thanks for the reply. I'll do trio mode 2x for now as you suggest. Will update to family mode when/if it gets in the release. 

Will the trio mode change the genotypes or genotype-qualities relative to population mode called on a trio? Or is it "just" assigning a posterior for the denovo?

**Comment by brentp** [comment]
And one more question. I'm planning to call trios, where possible and families otherwise, then combine across families with the n+1 example you describe [here](https://luntergroup.github.io/octopus/docs/guides/models/population#calling-large-cohorts-and-the-n--1-problem). How far will that scale? Could that work for 100 samples? 1000? 10,000? Thanks again.

**Comment by dancooke** [comment]
> Will the trio mode change the genotypes or genotype-qualities relative to population mode called on a trio?

The trio mode has an inheritance-based model different to that used in the population model, so you'll get different genotype posteriors. Both models are presented in the methods section of the [paper](https://www.nature.com/articles/s41587-021-00861-3).

> I'm planning to call trios, where possible and families otherwise, then combine across families with the n+1 example you describe here. How far will that scale? Could that work for 100 samples? 1000? 10,000?

It's not something I've tested, but I'd expect 1000's of samples to work with default settings. If you find this isn't the case then feel free to open a new ticket and I'll look into it.

**Comment by brentp** [comment]
Thank you. I will give it a go. And that brings another question:

is there utility in using `--bamout ... --bamout-type FULL` in the first octopus run for each sample (whether it's via trio mode or not)and then using that realigned bam as input to the later octopus runs (with groups of ~20 as prescribed in the docs).

**Comment by dancooke** [comment]
> is there utility in using --bamout ... --bamout-type FULL in the first octopus run for each sample (whether it's via trio mode or not)and then using that realigned bam as input to the later octopus runs

No, since reads are always realigned internally and _de novo_ variant discovery is disabled with the `--disable-denovo-variant-discovery` option (if this wasn't the case then there may be some benefit due to fewer spurious candidates from misaligned reads).

**Comment by brentp** [comment]
understood. cheers.
