### ISSUE TITLE
Spanning deletions

### ISSUE THREAD

**Issue by azzaea** [luntergroup/octopus#215]
Hello,
I'm using Octopus to call variants from a single sample, and have the ALT allele in my resulting file in more than 1 location suggesting two possible spanning deletions. I may be missing something, but would you advise on how to distinguish those 2 deletions?
```
chr1      24266119        .       AGGATGGAT       *,*     551     PASS    AC=1,1;AN=2;DP=72;MQ=49;NS=1;RFAQ_ALL=7.45      GT:GQ:DP:MQ:PS:PQ:RFAQ:RFGQ:FT  1|2:6:72:49:24266066:100:7.45:.:PASS
```
Thank you,
Azza

**Comment by dancooke** [comment]
Hi, the meaning of multiple spanning deletions is covered in the docs [here](https://luntergroup.github.io/octopus/docs/guides/advanced/vcf/#multiple--records).

**Comment by sstadick** [comment]
Just a note in case others come across this for the same reason as me.

HTSJDK was unwilling to parse a multiple spanning deletion of the type mentioned above:

```
Exception in thread "main" htsjdk.tribble.TribbleException: The provided VCF file is malformed at approximately line number 120593: Duplicate allele added to VariantContext: *, for input source:
```

Running `bcftools norm --do-not-normalize --multiallelics-` to split multiallelics allows HTSJDK to proceed.

**Comment by bobamess** [comment]
According to https://samtools.github.io/bcftools/bcftools.html the should be a space after `--multiallelics` as in the line below
`bcftools norm --do-not-normalize --multiallelics -`
Without the space you get an error like:
`norm: unrecognized option '--multiallelics-'`
