### ISSUE TITLE
Population mode with individuals of different ploidy

### ISSUE THREAD

**Issue by qhelleu** [luntergroup/octopus#221]
Hi,
Is it possible to run the population mode with individuals with different ploidy for all chromosomes?
Thanks.

**Comment by dancooke** [comment]
Yes.

**Comment by qhelleu** [comment]
How do you do?

**Comment by dancooke** [comment]
Use the [`--contig-ploidies`](https://luntergroup.github.io/octopus/docs/cli#--contig-ploidies) option.
