### ISSUE TITLE
Variant Calling in Low-Complexity Regions

### ISSUE THREAD

**Issue by zhoudreames** [luntergroup/octopus#222]
there are some variants where located in Low-Complexity Regions  can not be identified by using octopus software. how to solve it ？ thanks ~
![image](https://user-images.githubusercontent.com/54714639/145782089-41bec99a-efdf-4103-ab37-06a5c332341d.png)

**Comment by aquaskyline** [comment]
What's the truth variant  at the position?

**Comment by zhoudreames** [comment]
> What's the truth variant at the position?

yes ,this variants were support by hifi data.

**Comment by zhoudreames** [comment]
I using many Illumina variants caller can not  identity such variants ，whether  those variations located in such areas themselves are difficult to detect ？and is there any way to deal with it ？

**Comment by dancooke** [comment]
Looks like all reads spanning this locus have mapping quality 0, so there is at least one other location where they map equally well. I'm not aware of any mapping-based variant caller that will attempt to use MQ0 reads (by default). If you really want to call this region then you can add the options `--min-mapping-quality 0 --dont-model-mapping-quality`, but don't expect reliable calls.

**Comment by zhoudreames** [comment]
> Looks like all reads spanning this locus have mapping quality 0, so there is at least one other location where they map equally well. I'm not aware of any mapping-based variant caller that will attempt to use MQ0 reads (by default). If you really want to call this region then you can add the options `--min-mapping-quality 0 --dont-model-mapping-quality`, but don't expect reliable calls.

thanks~
