### ISSUE TITLE
how to select a better qulity variant from Spanning alleles

### ISSUE THREAD

**Issue by zhoudreames** [luntergroup/octopus#223]
I only want to save one variant possessed the best  calling qulity from spanning alleles，how to batch process it？ thanks~
![image](https://user-images.githubusercontent.com/54714639/146139559-b73640d5-a285-4029-8349-79add78c3f4a.png)

**Comment by dancooke** [comment]
There's no way to do this with Octopus, but I'm sure you can write a script using [pysam](https://pysam.readthedocs.io/en/latest/) that does what you want.

**Comment by zhoudreames** [comment]
thanks ~
