### ISSUE TITLE
Installation error - please advise

### ISSUE THREAD

**Issue by sprakashUTH** [luntergroup/octopus#224]
The system is: Linux - 3.10.0-1160.45.1.el7.x86_64 - x86_64

install.py gave these errors:

Last 15 lines from /home1/03437/sprakash/.cache/Homebrew/Logs/binutils/02.make:
./libtool: fork: retry: Resource temporarily unavailable
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DBINDIR=\"/work/03437/sprakash/lonestar/apps/octopus/build/brew/Cellar/binutils/2.37/bin\" -DLIBDIR=\"/work/03437/sprakash/lonestar/apps/octopus/build/brew/Cellar/binutils/2.37/lib\" -I. -I. -I./../include -DHAVE_all_vecs -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -g -O2 -c coff-tic4x.c -o coff-tic4x.o
./libtool: fork: retry: Resource temporarily unavailable
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DBINDIR=\"/work/03437/sprakash/lonestar/apps/octopus/build/brew/Cellar/binutils/2.37/bin\" -DLIBDIR=\"/work/03437/sprakash/lonestar/apps/octopus/build/brew/Cellar/binutils/2.37/lib\" -I. -I. -I./../include -DHAVE_all_vecs -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -g -O2 -c coff-tic54x.c -o coff-tic54x.o
./libtool: fork: retry: Resource temporarily unavailable
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DBINDIR=\"/work/03437/sprakash/lonestar/apps/octopus/build/brew/Cellar/binutils/2.37/bin\" -DLIBDIR=\"/work/03437/sprakash/lonestar/apps/octopus/build/brew/Cellar/binutils/2.37/lib\" -I. -I. -I./../include -DHAVE_all_vecs -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -g -O2 -c coff-tic30.c -o coff-tic30.o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -DBINDIR=\"/work/03437/sprakash/lonestar/apps/octopus/build/brew/Cellar/binutils/2.37/bin\" -DLIBDIR=\"/work/03437/sprakash/lonestar/apps/octopus/build/brew/Cellar/binutils/2.37/lib\" -I. -I. -I./../include -DHAVE_all_vecs -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -g -O2 -c coff-z80.c -o coff-z80.o
make[4]: Leaving directory '/tmp/binutils-20211216-690476-ldb3p/binutils-2.37/bfd'
make[3]: *** [Makefile:1643: all-recursive] Error 1
make[3]: Leaving directory '/tmp/binutils-20211216-690476-ldb3p/binutils-2.37/bfd'
make[2]: *** [Makefile:1174: all] Error 2
make[2]: Leaving directory '/tmp/binutils-20211216-690476-ldb3p/binutils-2.37/bfd'
make[1]: *** [Makefile:2817: all-bfd] Error 2
make[1]: Leaving directory '/tmp/binutils-20211216-690476-ldb3p/binutils-2.37'
make: *** [Makefile:903: all] Error 2

READ THIS: https://docs.brew.sh/Troubleshooting

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home1/03437/sprakash/miniconda3/bin/x86_64-conda-linux-gnu-cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home1/03437/sprakash/miniconda3/bin/x86_64-conda-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type: Release
-- Installation prefix: /work/03437/sprakash/lonestar/apps/octopus/bin
CMake Error at build/brew/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR iostreams) (Required is at
  least version "1.65")
Call Stack (most recent call first):
  build/brew/Cellar/cmake/3.22.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  build/brew/Cellar/cmake/3.22.1/share/cmake/Modules/FindBoost.cmake:2360 (find_package_handle_standard_args)
  lib/ranger/CMakeLists.txt:35 (find_package)

-- Configuring incomplete, errors occurred!
See also "/work/03437/sprakash/lonestar/apps/octopus/build/CMakeFiles/CMakeOutput.log".

**Comment by dancooke** [comment]
Hi, please provide all the information asked for in the issue template (particularly your installation command).

**Comment by sprakashUTH** [comment]
I solved this already, forgot to close. Sorry!
