### ISSUE TITLE
When would an insertion's base be called as N?

### ISSUE THREAD

**Issue by js72587** [luntergroup/octopus#234]
I have a couple of occurrences in indel calling where one base in an insertion was called as N (as a made-up but similar example, expected is AGGGTCC but called was AGGGTNC). Could you point me to the code where, or documentation of possible reasons why, this would happen? I tried searching but was unable to find it due to difficulties of searching for mentions of "N". Thanks so much.

**Comment by dancooke** [comment]
This can happen if `N` is present in the input reads - have you looked at the read pileups? You can use the [`--bamout`](https://luntergroup.github.io/octopus/docs/guides/bamout) to get realigned reads.

**Comment by js72587** [comment]
Thank you!
