### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by looxon93** [luntergroup/octopus#24]
Hi! I am having an issue with running Octopus somatic calling. It seems to be problem with memory since I can not set optimal parameters for memory and program crashes with code 139. I run it on instance with 30 Gb of RAM and 16 CPUs. BAM files have 30 Gb in total. Here is my command line: 
`octopus -R human_g1k_v37_decoy.fasta -I normal.bam tumor.bam -t example.bed -N normal --threads 16 -X 8000 -B 8` 

It seems it always come to 5% completed and it crashes. 
Here is print from log:

```
[2018-02-02 12:07:24] <INFO> ------------------------------------------------------------------------
[2018-02-02 12:07:24] <INFO> octopus v0.3.3-alpha
[2018-02-02 12:07:24] <INFO> Copyright (c) 2017 University of Oxford
[2018-02-02 12:07:24] <INFO> ------------------------------------------------------------------------
[2018-02-02 12:13:38] <INFO> Done initialising calling components in 6.23m
[2018-02-02 12:13:38] <INFO> Detected 2 samples: "Tumor" "Normal"
[2018-02-02 12:13:38] <INFO> Invoked calling model: cancer
[2018-02-02 12:13:38] <INFO> Processing 59,892,486bp with 16 threads
[2018-02-02 12:13:38] <INFO> Writing filtered calls to stdout
[2018-02-02 12:13:38] <INFO> ------------------------------------------------------------------------
[2018-02-02 12:13:38] <INFO>      current      |                   |     time      |     estimated   
[2018-02-02 12:13:38] <INFO>      position     |     completed     |     taken     |     ttc         
[2018-02-02 12:13:38] <INFO> ------------------------------------------------------------------------
[2018-02-02 12:14:22] <INFO>      1:16475621             1.0%             43s           1.18h
[2018-02-02 12:15:31] <INFO>      1:32145441             2.0%           1.86m           1.86h
[2018-02-02 12:16:58] <INFO>      1:45222003             3.0%           3.31m           2.35h
[2018-02-02 12:18:24] <INFO>      1:68954864             4.0%           4.75m           2.30h
[2018-02-02 12:18:28] <INFO>      1:75065676             4.1%           4.81m           2.23h
[2018-02-02 12:18:39] <INFO>      1:78384058             4.2%           5.00m           2.26h
[2018-02-02 12:21:06] <INFO>     1:111860800             5.2%           7.45m           2.73h
```

I tried it also on my computer with smaller BAM files  only on chromosome 21 and it also crashes with message: killed. 

Can you help me set best parameters so program could work or is there a bug? 

Thanks!

**Comment by dancooke** [comment]
Hi Luka,

Can you please double check your command line inputs for the reference cache sizes `-X` and the read buffer size `-B`? Both these commands expect the units you're giving, in bytes. So values of `8000` and `8` would be just 8000 and 8 bytes, respectively.

About setting these parameters.. When using multiple threads, octopus shares the maximum buffer size equally between threads, so a bigger read buffer size will result in larger tasks for each thread. There are pros and cons of having larger thread tasks; on the one hand it means less overhead (thread management, disk I/O), but on the other hand it may result in uneven work load between threads, especially if one thread has lots of difficult regions. So usually there is diminishing returns of having a bigger read buffer size. Probably for your use-case the defaults would be fine. You only really want to consider increasing it if you have very high read coverage, or are calling many samples.

Having said that, you've certainly hit a bug as exit code 139 is a memory violation. If you can provide me with a minimal subset of the BAMs that trigger the issue, I can probably very quickly identify the problem. If that's not possible, then if you can run the smaller example (chromosome 21) with the same input but add the `--debug` command, this will produce a debug log file (called `octopus_debug.log` by default). If you could post this log file, that will help me track down the issue.

Many thanks,
Dan

**Comment by dancooke** [comment]
Just to be clear, for the options `-X` and `-B` you can specify the units (e.g. kilobytes). So you could write `500KB`, `500KiB`, or `500Kb` for 500 kilobytes, and `8GB`, `8Gb`, or `8GiB` for 8 gigabytes. But if you don't specify the units, bytes are assumed.

**Comment by looxon93** [comment]
Hey Daniel,

thank you for your fast response. I corrected these inputs, and gave it like you said in GB, but again it breaks on same spot, after 5% of files processed on big BAM files. 

I can give these small BAM files. Can I share them with Google drive with you?
Here is my command line:
`octopus -R human_g1k_v37_decoy.fasta -I merged-normal.bam merged-tumor.bam -T 21 -N HCC1143BL`

**Comment by dancooke** [comment]
Great. Google drive works for me, my Google email is dan.cooke89@gmail.com.

**Comment by dancooke** [comment]
Hi Luka, thanks for sending the BAMs. I can't seem to replicate the problem on either my OS X or Ubuntu machines, and my debugger isn't showing any memory access problems.

Could you please confirm the following:

- Which version of octopus you're using (and which branch you built if you cloned the Git repo).
- Your operating system (incl version).
- Which compiler you used to build octopus (incl version).
- Which version of htslib you're using.

If you could also re-run your smaller example with the `--debug` command, and post the resulting log file (you should be able to post on here as it won't be too large), that would also be helpful.

Thanks for you help.

**Comment by looxon93** [comment]
I run it in docker container that I build with your docker you made in #20. I build docker image and copied files in container, so I can run octopus there. 

Here is a command line:
`[root@6418d9be8b87 opt]# octopus -R human_g1k_v37_decoy.fasta -I merged-normal.bam merged-tumor.bam -T 21 -N HCC1143BL --debug`
Error I get is `Killed` and error log is empty.

**Comment by dancooke** [comment]
Ah, then it's possible the problem is with the Docker container. What options did you use to build the Docker container? [This issues](https://github.com/moby/moby/issues/22211) sounds similar to the one you're having. The solution was to give the Docker container more memory.

**Comment by dancooke** [comment]
I can confirm the problem is due to insufficient memory available for the Docker container (2GB by default). You can resolve this by [increasing the memory allocated to the container](https://stackoverflow.com/questions/44533319/how-to-assign-more-memory-to-docker-container).

So another possible work-around is to set the read buffer size very small (e.g. `50MB` per thread, so ~ `1G` for 16 threads). Since this is exome sequencing, you really don't need a large read buffer size, and may even find a speedup from having it smaller.
