### ISSUE TITLE
Failed to download forest somatic.v0.7.4.forest.gz

### ISSUE THREAD

**Issue by ghost** [luntergroup/octopus#259]
Hello,

the title is pretty self-explanatory. The command

`/install.py --dependencies --forests` failed. 

Is there an issue with the cloud storage, such as it has moved, is not paid for any more, etc? 

Thanks! 

EDIT2: seems to be a billing issue on the Google cloud

**Comment by dancooke** [comment]
Hi, Sorry it's taken so long to address this - there was a billing problem with my Google Cloud account. I'll look to move the files over to Zenodo as suggested in #261 asap.

**Comment by gambalab** [comment]
An other free solution were you can put useful files is figshare or github with LFS (max file dimension is 2GB with the free plan)

**Comment by ghost** [comment]
Tanks Dan for taking the time to fix this. Octopus is an awesome tool! we need it.

**Comment by ghost** [comment]
Hello

do you have an idea about when this will be fixed? If I (and the community) can help, please let us know. Octopus is an awesome SNP callers, we must preserve it! Thank you

**Comment by dancooke** [comment]
I've added the forest files to the [repo](https://github.com/luntergroup/octopus/tree/develop/resources/forests) with LFS.

**Comment by ghost** [comment]
> 

is it normal the files ends in .gz but are NOT compressed? Also, upon inspection they look like HTML files but I don't see where are the decisions. I am no expert though, but could you kindly double check you haven't uploaded the wrong file? Which would explain while all my call returns empty vcf. Thanks

**Comment by jelber2** [comment]
I think maybe you are trying to download the pointers to the files as they were uploaded with `git lfs`. 

As far as I know, you need to do the following, but note the error message at the bottom

```bash
git clone https://github.com/luntergroup/octopus
cd octopus/
# you need to install git-lfs
git lfs pull

batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                               
Failed to fetch some objects from 'https://github.com/luntergroup/octopus.git/info/lfs'
```
So, nothing more can be done until the data quota is increased or perhaps refreshes (not sure if it is a monthly thing?)

**Comment by ghost** [comment]
Oh, ok, thanks, so we still don't have the forest files available.

git lfs pull returns nothing for me 

EDIT: ok for an unknown reason I had to redownload the repo. And I have the same error message as you. 

@dancooke Is there a way we can help you? Maybe Zenodo can be a solution?
https://zenodo.org/ (I am not involved with zenodo I have no conflict of interest).
