### ISSUE TITLE
Use with Nanopore long reads

### ISSUE THREAD

**Issue by pabloangulo7** [luntergroup/octopus#281]
Hello,

Would be possible to perform a SNP variant calling using Nanopore sequencing data?  What parameters would have to be modified and how could a custom error model based on Nanopore be created? 

Thanks in advance,

Pablo

**Comment by jelber2** [comment]
It is indeed possible, but I had tried not with standard raw Nanopore R10.4.1 SUP reads, rather Herro-corrected SUP reads. I made a custom error model/profile, but in the end, I got better performance from the PacBio CCS configuration that includes a PacBio error model. With this PacBio error model, I even trained my own Random Forest, but I never got Indel F1 scores higher than 0.84 , which I had already gotten with Clair3 . The SNP F1 score was I think 0.996 , comparable again to Clair3 results, which is faster. My advice is to stick to Clair3 for Nanopore R10.4.1 reads, but it is not intended for amplicons as far as I know (not personally tested though).

**Comment by pabloangulo7** [comment]
Ok, I will try that. Thank you for the help

**Comment by ewoutcrombez** [comment]
Hello,

I would also like to use Octopus on Herro-corrected SUP reads. My samples are polyploid so it is not possible to use Clair3, which is specifically trained on diploid data. Do you think I can use Octopus for this?
Many thanks in advance!

**Comment by jelber2** [comment]
I think you could use octopus in the sense that it would work, but I have no idea of the precision and recall you would get for SNVs and indels without training a random forest classifier to filter out false positives. I cannot remember how well octopus worked without a random forest (i.e., to run Octopus with PacBio CCS settings but with Herro-corrected SUP reads as input and the diploid, germline calling mode), but my guess is a good random forest classifier would be needed. @ewoutcrombez

**Comment by ewoutcrombez** [comment]
Thank you for your response @jelber2! I see that there also is a polyploid random forest model on the Google Cloud. Couldn't I use that one then to filter out false positives? Or do you suspect specific problems because of the sequencing platform?

**Comment by jelber2** [comment]
I was not aware any of the random forest models were actually, right now available from @dancooke . I would not use it because of it being a different sequencing technology and also perhaps because of a different species (although I would think the sequencing technology would be the biggest issue).
