### ISSUE TITLE
"illegal hardware instruction" when running Octopus installed via Conda

### ISSUE THREAD

**Issue by LiptonTipton** [luntergroup/octopus#34]
**Describe the bug**
Following official instructions I succesfully installed Octopus with conda.
```shell
$ wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
$ bash ./Miniconda3-latest-Linux-x86_64.sh -b -p venv
$./venv/bin/conda install -c conda-forge -c bioconda octopus  
```
I get error when trying to run Octopus.

**Command**
Command line to run octopus:
```shell
$ venv/bin/octopus -h
[1]    10679 illegal hardware instruction (core dumped)  venv/bin/octopus -h
```

**Desktop (please complete the following information):**
 - OS: [Ubuntu 14.04]
 - Version [latest, as of 6 September 2018]
 - Reference [N/A]

**Additional context**
Not sure if it helps:
* Exactly the same behavior is observed when installing Octopus with another installation of Conda.
* In Nautilus the octopus file is recognized as "shared library (application/x-sharedlib)"

**Comment by dancooke** [comment]
This looks like to same problem as the one described in issue #27. As Brad explains, this is a problem with the Bioconda build process and not with Octopus per-se. You could try following Brad's advice on that issue, or opening a Bioconda issue if that doesn't work.
