### ISSUE TITLE
cmake3 note found on CentOS

### ISSUE THREAD

**Issue by datakid** [luntergroup/octopus#37]
**Describe the bug**
Install fails if it can't find cmake of version.

Only searches for cmake.

In CentOS - and I presume RedHat - cmake is used for version 2, cmake3 is for version 3.

Need to edit line 98 of scripts/install.py from

`ret = call(["cmake"] + cmake_options + [".."])`

to 

`ret = call(["cmake3"] + cmake_options + [".."])`

and that check passes.

**Comment by dancooke** [comment]
Addressed in 30a3ffb11ad216e108efefcd70549130939655bb and is available on develop branch. Please re-open if any issues.
