### ISSUE TITLE
HTSLIB not found

### ISSUE THREAD

**Issue by datakid** [luntergroup/octopus#38]
I'm getting HTSlib not found errors.

We have a number of versions of HTSLIB installed in a non regular path. We have Environment Modules designed to load HTSLIB into the environment - I loaded that module:

```
LIBRARY_PATH=/config/binaries/htslib/1.9/include:/config/binaries/boost/1.68.0/lib
LD_LIBRARY_PATH=/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/opt/rh/devtoolset-7/root/usr/lib64/dyninst:/opt/rh/devtoolset-7/root/usr/lib/dyninst:/opt/rh/devtoolset-7/root/usr/lib64:/opt/rh/devtoolset-7/root/usr/lib:/config/binaries/htslib/1.9/lib
PATH=/opt/rh/devtoolset-7/root/usr/bin:/config/binaries/htslib/1.9/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/puppetlabs/bin:/root/bin:/root/bin
```

despite this, I still get the error:
```
_LMFILES_=/config/modulefiles/htslib/1.9
LOADEDMODULES=htslib/1.9

HTSlib_INCLUDE_DIR=HTSlib_INCLUDE_DIR-NOTFOUND
HTSlib_LIBRARY=HTSlib_LIBRARY-NOTFOUND
CMake Error at build/cmake/modules/FindHTSlib.cmake:67 (message):
  Required library HTSlib NOT FOUND.

  Install the library (dev version) and try again.  If the library is already
  installed, use ccmake to set the missing variables manually.
Call Stack (most recent call first):
  build/cmake/modules/FindHTSlib.cmake:137 (libfind_process)
  src/CMakeLists.txt:659 (find_package)


-- Configuring incomplete, errors occurred!
See also "/config/source/octopus/build/CMakeFiles/CMakeOutput.log".
See also "/config/source/octopus/build/CMakeFiles/CMakeError.log".
```

So I created the asked for env vars:
```
root@vmpr-res-utils:/config/source/octopus#
==> env | grep HTS
HTSlib_INCLUDE_DIR=/config/binaries/htslib/1.9/include
HTSlib_LIBRARY=/config/binaries/htslib/1.9/lib
```

But I got the same error again.

(also worth noting in that first code snippet that I've also got the boost module loaded, but I still need to pass --boost to the install script)

Am I putting the wrong values into HTSlib_* or do I need to use a different environment var?

**Comment by dancooke** [comment]
Could you try:

```shell
export HTSLIB_ROOT=/config/binaries/htslib/1.9
```

**Comment by dancooke** [comment]
I've added a `--htslib` option to the Python installer in 93ba0000b56cad3c490d3e8ce5b400180a6a0e46. You should be able to use:

```shell
./install.py --htslib /config/binaries/htslib/1.9
````

**Comment by datakid** [comment]
> Could you try:
> 
> ```shell
> export HTSLIB_ROOT=/config/binaries/htslib/1.9
> ```

Yes, that worked - thanks for the prompt response and fixes, appreciated. Installing now.

**Comment by datakid** [comment]
FWIW, in CentOS people will need to `yum install devtoolset-7` and then execute `scl enable devtoolset-7 bash` in order to get a dev env with the required up to date C++ compilers
