### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by DataOmics76** [luntergroup/octopus#39]
Dear Sr:
When I try to start the program I get Illegal instruction (core dumped) message.

Command line to run octopus:
```shell
cri@cri-To-be-filled-by-O-E-M: venv/bin/conda install -c conda-forge -c bioconda octopus
Solving environment: done

# All requested packages already installed.

cri@cri-To-be-filled-by-O-E-M: venv/bin/octopus -h
Illegal instruction (core dumped)

```
 - OS: [ Ubuntu 16.04 LTS]

Thanks for the help.

**Comment by dancooke** [comment]
Hi, this issue has been previously been reported (#27 and #34). It is an issue with the Bioconda build, not with Octopus. I'll open an issue on Bioconda, hopefully one of the maintainers can help.
