### ISSUE TITLE
octopus-0.5.2-beta compilation, Centos 6.9

### ISSUE THREAD

**Issue by jbsysadmin** [luntergroup/octopus#48]
Regarding #43, "octopus-0.5.2-beta does not compile, Centos 6.9 " I finally was able to compile Octopus using gcc 7.3 & rebuilt boost 1.68.

References for that choice of compiler: 
   https://www.mail-archive.com/gcc-bugs@gcc.gnu.org/msg579188.html
   https://forum.freecadweb.org/viewtopic.php?t=27399&start=10

I posted this here for information purpose. I can't be sure if you receive messages on closed tickets.
Please close as needed.

**Comment by dancooke** [comment]
Thanks for the feedback. Glad to hear that you got things working.
