### ISSUE TITLE
N+1 calling (or gVCF calling)

### ISSUE THREAD

**Issue by shalabhsuman** [luntergroup/octopus#49]
Is the tool optimized to perform variant calling (Exome or Whole Genome) on a large cohort of samples (>500) using N+1 method? Is it possible to have outputs in gVCF format?

**Comment by dancooke** [comment]
The "N + 1" problem is discussed in the wiki pages [here](
https://github.com/luntergroup/octopus/wiki/Calling-models:-Population#calling-large-cohorts-and-the-n--1-problem). Calling of large cohorts has not been tested, and joint calling of sex chromosomes is currently under development (see [this issue](https://github.com/luntergroup/octopus/issues/12)).

The current develop branch version supports reference calling (see [this wiki page](https://github.com/luntergroup/octopus/wiki/How-to:-Call-reference-sequence)). Note however that Octopus does not report genotype likelihoods, so you will not be able to use GATK-style gVCF merging.

**Comment by simoncawley** [comment]
Hi Dan, I'm interested in trying out Octopus for calling reference, I was excited to see the link you posted above but sadly it leads to a blank page.  Is there any documentation available in another location?
