### ISSUE TITLE
cmake fails

### ISSUE THREAD

**Issue by sujaikumar** [luntergroup/octopus#5]
Hi. Thanks for releasing this. Looks terrific!

While installing on Ubuntu linux (16.04), I got all the dependencies installed first (including the latest cmake 3.5.2, htslib etc), but it fails after initially chugging along fine.

Any suggestions on what I might be doing wrong?

    /exports/software/octopus$ ./install.py 
    -- Build type is Release
    -- Looking for pthread.h
    -- Looking for pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - not found
    -- Looking for pthread_create in pthreads
    -- Looking for pthread_create in pthreads - not found
    -- Looking for pthread_create in pthread
    -- Looking for pthread_create in pthread - found
    -- Found Threads: TRUE  
    -- Boost version: 1.58.0
    -- Found the following Boost libraries:
    --   system
    --   filesystem
    --   program_options
    --   date_time
    --   log_setup
    --   log
    --   iostreams
    --   timer
    --   thread
    --   regex
    --   chrono
    --   atomic
    -- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
    -- Found HTSlib 
    --    HTSlib include dirs: /usr/local/include/htslib;/usr/include
    --    HTSlib libraries: /usr/local/lib/libhts.so;/usr/lib/x86_64-linux-gnu/libz.so
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /exports/software/octopus/build
    Scanning dependencies of target libdivsufsort
    [  0%] Building C object lib/tandem/libdivsufsort/CMakeFiles/libdivsufsort.dir/divsufsort.c.o
    [  1%] Building C object lib/tandem/libdivsufsort/CMakeFiles/libdivsufsort.dir/sssort.c.o
    [  2%] Building C object lib/tandem/libdivsufsort/CMakeFiles/libdivsufsort.dir/trsort.c.o
    [  3%] Building C object lib/tandem/libdivsufsort/CMakeFiles/libdivsufsort.dir/utils.c.o
    [  4%] Linking C static library liblibdivsufsort.a
    [  4%] Built target libdivsufsort
    Scanning dependencies of target tandem
    [  5%] Building CXX object lib/tandem/CMakeFiles/tandem.dir/tandem.cpp.o
    [  6%] Linking CXX static library libtandem.a
    [  6%] Built target tandem
    Scanning dependencies of target octopus
    [  7%] Building CXX object src/CMakeFiles/octopus.dir/main.cpp.o
    [  7%] Building CXX object src/CMakeFiles/octopus.dir/config/config.cpp.o
    [  8%] Building CXX object src/CMakeFiles/octopus.dir/config/common.cpp.o
    [  9%] Building CXX object src/CMakeFiles/octopus.dir/config/option_parser.cpp.o
    [ 10%] Building CXX object src/CMakeFiles/octopus.dir/config/option_collation.cpp.o
    [ 11%] Building CXX object src/CMakeFiles/octopus.dir/config/octopus_vcf.cpp.o
    [ 12%] Building CXX object src/CMakeFiles/octopus.dir/exceptions/error.cpp.o
    [ 12%] Building CXX object src/CMakeFiles/octopus.dir/exceptions/missing_file_error.cpp.o
    [ 13%] Building CXX object src/CMakeFiles/octopus.dir/exceptions/malformed_file_error.cpp.o
    [ 14%] Building CXX object src/CMakeFiles/octopus.dir/exceptions/missing_index_error.cpp.o
    [ 15%] Building CXX object src/CMakeFiles/octopus.dir/exceptions/unwritable_file_error.cpp.o
    [ 16%] Building CXX object src/CMakeFiles/octopus.dir/basics/cigar_string.cpp.o
    [ 17%] Building CXX object src/CMakeFiles/octopus.dir/basics/aligned_read.cpp.o
    [ 17%] Building CXX object src/CMakeFiles/octopus.dir/basics/ploidy_map.cpp.o
    [ 18%] Building CXX object src/CMakeFiles/octopus.dir/logging/logging.cpp.o
    [ 19%] Building CXX object src/CMakeFiles/octopus.dir/logging/progress_meter.cpp.o
    [ 20%] Building CXX object src/CMakeFiles/octopus.dir/logging/error_handler.cpp.o
    [ 21%] Building CXX object src/CMakeFiles/octopus.dir/logging/main_logging.cpp.o
    [ 22%] Building CXX object src/CMakeFiles/octopus.dir/io/reference/caching_fasta.cpp.o
    [ 22%] Building CXX object src/CMakeFiles/octopus.dir/io/reference/fasta.cpp.o
    [ 23%] Building CXX object src/CMakeFiles/octopus.dir/io/reference/reference_genome.cpp.o
    [ 24%] Building CXX object src/CMakeFiles/octopus.dir/io/reference/threadsafe_fasta.cpp.o
    [ 25%] Building CXX object src/CMakeFiles/octopus.dir/io/region/region_parser.cpp.o
    [ 26%] Building CXX object src/CMakeFiles/octopus.dir/io/read/htslib_sam_facade.cpp.o
    /exports/software/octopus/src/io/read/htslib_sam_facade.cpp: In member function ‘octopus::AlignedRead octopus::io::HtslibSamFacade::HtslibIterator::operator*() const’:
    /exports/software/octopus/src/io/read/htslib_sam_facade.cpp:956:28: warning: narrowing conversion of ‘octopus::io::mapping_quality((* & info))’ from ‘unsigned int’ to ‘octopus::AlignedRead::MappingQuality {aka unsigned char}’ inside { } [-Wnarrowing]
                 mapping_quality(info),
                                ^
    /exports/software/octopus/src/io/read/htslib_sam_facade.cpp:973:28: warning: narrowing conversion of ‘octopus::io::mapping_quality((* & info))’ from ‘unsigned int’ to ‘octopus::AlignedRead::MappingQuality {aka unsigned char}’ inside { } [-Wnarrowing]
                 mapping_quality(info),
                                ^
    [ 27%] Building CXX object src/CMakeFiles/octopus.dir/io/read/read_manager.cpp.o
    [ 27%] Building CXX object src/CMakeFiles/octopus.dir/io/read/read_reader.cpp.o
    [ 28%] Building CXX object src/CMakeFiles/octopus.dir/io/variant/htslib_bcf_facade.cpp.o
    /exports/software/octopus/src/io/variant/htslib_bcf_facade.cpp: In instantiation of ‘octopus::set_samples(const bcf_hdr_t*, bcf1_t*, const octopus::VcfRecord&, const std::vector<std::__cxx11::basic_string<char> >&)::<lambda(const auto:12&)> [with auto:12 = std::__cxx11::basic_string<char>]’:
    /usr/include/c++/5/bits/stl_algo.h:3767:5:   required from ‘_Funct std::for_each(_IIter, _IIter, _Funct) [with _IIter = __gnu_cxx::__normal_iterator<const std::__cxx11::basic_string<char>*, std::vector<std::__cxx11::basic_string<char> > >; _Funct = octopus::set_samples(const bcf_hdr_t*, bcf1_t*, const octopus::VcfRecord&, const std::vector<std::__cxx11::basic_string<char> >&)::<lambda(const auto:12&)>]’
    /exports/software/octopus/src/io/variant/htslib_bcf_facade.cpp:891:6:   required from here
    /exports/software/octopus/src/io/variant/htslib_bcf_facade.cpp:845:45: internal compiler error: Segmentation fault
             const auto num_values = num_samples * static_cast<int>(source.format_cardinality(key));
                                                 ^
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
    src/CMakeFiles/octopus.dir/build.make:686: recipe for target 'src/CMakeFiles/octopus.dir/io/variant/htslib_bcf_facade.cpp.o' failed
    make[2]: *** [src/CMakeFiles/octopus.dir/io/variant/htslib_bcf_facade.cpp.o] Error 1
    CMakeFiles/Makefile2:216: recipe for target 'src/CMakeFiles/octopus.dir/all' failed
    make[1]: *** [src/CMakeFiles/octopus.dir/all] Error 2
    Makefile:116: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by dancooke** [comment]
Hi Sujai,

This is because you're using GCC 5, which although advertises itself as C++14 compliant, in reality is not. This tricks CMake into thinking it's an okay compiler to use, which results in the error you're seeing. To resolve this you will need a newer compiler, GCC 6.2+ and Clang 3.8+ are currently known to work, and Clang is recommended over GCC. You will then need to set the compiler explicitly, e.g:

``
$ ./install.py --compiler clang++-3.8
``

Or if `clang++-3.8` is not on your `$PATH` then set the full path, e.g:

``
$ ./install.py --compiler /usr/bin/clang++-3.8
``

This seems to be a common issue, so I'll set explicit compiler version requirements in the next release rather than relying on CMake.

Best,

Dan

**Comment by sujaikumar** [comment]
Got it! Thanks - I did see that in the requirements and installed it, but didn't explicitly set it anywhere. 

Installed fine this time. Thanks :-)
