### ISSUE TITLE
Segfault occurring during somatic variant calling

### ISSUE THREAD

**Issue by pjongeneel** [luntergroup/octopus#50]
Hello there,

I've been experiencing segfaults when trying to run octopus for certain chromosomes on my data.

For instance the command line: 
/octopus/0.5.2/venv/bin/octopus -C individual -R /hs37d5/raw/hs37d5.fa -I /pipeline_output/Alignment/HCC38.bam /pipeline_output/Alignment/HCC38BL.bam --normal-sample HCC38BL --threads 4 --forest-file germline.forest --somatic-forest-file somatic.forest --regions-file 5.bed --working-directory /Octopus --output /Octopus/HCC38.octopus.chromosome_5.vcf --legacy

will cause a segfault as pasted below
[2019-01-28 10:48:09] <INFO>      5:74985048            32.6%           1h 27m            3h 13m
[2019-01-28 10:48:16] <INFO>      5:76607329            33.6%           1h 27m             3h 5m
[2019-01-28 10:48:20] <INFO>      5:78351905            34.6%           1h 27m            2h 56m
[2019-01-28 10:48:39] <INFO>      5:79287160            35.6%           1h 28m            2h 49m
[2019-01-28 10:49:01] <INFO>      5:80150148            36.6%           1h 28m            2h 43m
[2019-01-28 10:49:48] <INFO>      5:82649104            37.6%           1h 29m            2h 37m
[2019-01-28 10:50:13] <INFO>      5:87499037            38.6%           1h 29m            2h 31m
[2019-01-28 10:50:27] <INFO>      5:90070178            39.6%           1h 30m            2h 25m
[2019-01-28 10:50:53] <INFO>      5:94040933            40.6%           1h 30m            2h 20m
[2019-01-28 10:51:12] <INFO>      5:95145447            41.6%           1h 30m            2h 14m
[2019-01-28 10:51:47] <INFO>      5:96322489            42.6%           1h 31m             2h 9m
[2019-01-28 10:53:18] <INFO>     5:101707910            43.6%           1h 32m             2h 6m
Segmentation fault (core dumped)

Some chromosome bed files cause segfaults, and some dont. 5.bed causes a seg fault, 6.bed doesnt (see attached - renamed to .txt to allow attachment)

Any help would be appreciated 

[5.bed.txt](https://github.com/luntergroup/octopus/files/2805221/5.bed.txt)
[6.bed.txt](https://github.com/luntergroup/octopus/files/2805222/6.bed.txt)

**Comment by dancooke** [comment]
Thanks for the bug report. I'll need a few more details to resolve this:

1. How was Octopus installed?
2. Which operating system are you using?
3. What version of Octopus are you running, v0.5.2-beta?
4. Are these BAM files public, or can you share them?

A side note - you don't need the `-C individual` in this command as the `cancer` calling model is automatically invoked when `--normal-sample` is specified. The `individual` calling model is used for calling germline variants in a single sample, so isn't what you wanted here anyway.

**Comment by pjongeneel** [comment]
Thank you for the quick response! Also thanks for the tip surrounding the option specification.

Octopus was installed with:
wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh -b -p venv
venv/bin/conda install -c conda-forge -c bioconda octopus

Yes I do see octopus 0.5.2-beta when I do --version
OS is centOS 6 and I'll have to get back to you about the bams.

**Comment by pjongeneel** [comment]
https://drive.google.com/drive/folders/1MC0HXQvS6Kgfh8Po6-3NPfsY5PgDf1g6?usp=sharing

Split bam into chromosome 5 and 6 regions, so if you just run the 5.bed with 5.bams and the 6.bed with the 6.bams, I can confirm I still get a segfault for 5 but not 6.

**Comment by dancooke** [comment]
Thanks for sharing the data. I can replicate the segfault with v0.5.2-beta but not with v0.5.3-beta, leading me to believe that this bug has already been resolved. I'm just finalising some updates for v0.5.4-beta, which I will add to Bioconda. Alternatively you could try to install v0.5.3-beta - and then v0.5.4-beta when released - manually (see the [wiki](
https://github.com/luntergroup/octopus/wiki/Installation#quick-installation-with-python3-recommended) for instructions).

**Comment by pjongeneel** [comment]
Thank you so much! I really appreciate the help

**Comment by pjongeneel** [comment]
I'm having trouble compiling, do you know any timeline for 0.5.3 to be released on the bioconda package installer?

**Comment by pjongeneel** [comment]
Hey @dancooke, just checking in again. I've been attempting to build on centos for a few days with a clean docker image, but am still having problems due to requirements of gcc versioning and what not.
Just wanted to check if a prebuilt bioconda package was going to be release for 0.5.3b in order to overcome the segfault issue for my data.

**Comment by dancooke** [comment]
I'm not planning on putting 0.5.3b on Bioconda now as I'm going to release a newer version in the next few days (which I will put on Bioconda).

v0.5.3b came with an improved installation script (specifically the option `--install-dependencies`) that should make installation simple on most systems (see [this wiki page](
https://github.com/luntergroup/octopus/wiki/Installation#quick-installation-with-python3-recommended)). I'd recommend installing manually as you'll get a binary optimised for your system - unlike the Bioconda binary. Note if you're using a Docker container then you'll need to create a non-root sudo user to use this option (see my post [here](https://github.com/luntergroup/octopus/issues/43#issuecomment-447636718)). If you're still having trouble installing then please do submit a new issue.

**Comment by pjongeneel** [comment]
I do end up still having issues with the --install-dependencies and install script, even with the latest checkout, on a CentOs system. I will just wait for the new release on bioconda, thank you.

**Comment by dancooke** [comment]
@pjongeneel FYI. I've made multiple [pull requests](https://github.com/bioconda/bioconda-recipes/pull/13583) to Bioconda trying to get newer versions of Octopus added but there are issues with their Boost installation. Happy to try to assist installing Octopus from source (which is highly recommended for optimal performance anyway).

**Comment by dancooke** [comment]
Closing as I believe this is resolved in newer versions.
