### ISSUE TITLE
Octopus writes out unicode characters in the VCF header

### ISSUE THREAD

**Issue by ryanrichholt** [luntergroup/octopus#56]
**Describe the bug**
Octopus writes out unicode characters in the VCF header. The leaning quotes in the source code around the word "called" actually make it into the VCF headers downstream. This causes the resulting output VCF to contain unicode text, and breaks reading with Pysam.

Here: 
https://github.com/luntergroup/octopus/blob/66e4466350edb5c7c17c2eab218e46f28699293b/src/config/octopus_vcf.cpp#L26

and here:
https://github.com/luntergroup/octopus/blob/af6048fe79e2e214d0776e4fd5681b8938a447ec/src/io/variant/vcf_header.cpp#L407

Heres the pysam error

```
>>> vcf = pysam.VariantFile('test_data/raw_tool_vcfs/octopus.raw.vcf')
>>> print(vcf.header)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pysam/libcbcf.pyx", line 2042, in pysam.libcbcf.VariantHeader.__str__ (pysam/libcbcf.c:30689)
  File "pysam/libcutils.pyx", line 143, in pysam.libcutils.charptr_to_str_w_len (pysam/libcutils.c:3393)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1516: ordinal not in range(128)
```

And here's the offending header line:
```
##FORMAT=<ID=FT,Number=1,Type=String,Description="Sample genotype filter indicating if this genotype was “called”">
```

**Command**
Command line to run octopus:
```shell
$ octopus
```

**Desktop (please complete the following information):**
 - OS: [e.g. OSX High Sierra]
 - Version [e.g. v0.3.3-alpha]
 - Reference [e.g. hg19]

**Additional context**

**Comment by dancooke** [comment]
Thanks Ryan. Should be resolved in 886e3a3075f2d2e93cc32cae8eedc6e062151885. Please re-open if any further problems.
