### ISSUE TITLE
Random Forest file not accesible

### ISSUE THREAD

**Issue by XavierMialhe** [luntergroup/octopus#58]
**Describe the bug**
Despite the related issue created by delavefm, random forest files are not accessible from the cloud (from the link in the manual or from my command below)

**Command**
gsutil cp gs://luntergroup/octopus/forests/somatic.v0.6.2-beta.forest .
ServiceException: 401 Anonymous caller does not have storage.objects.get access to luntergroup/octopus/forests/somatic.v0.6.2-beta.forest.

**Desktop :**
OS: Ubuntu 18.10
version: v0.6.2-beta
Reference hg19

**Comment by dancooke** [comment]
Currently, only the latest release version of the forests are stored on Google Cloud (currently v0.6.3-beta). I'm thinking of a better way to version the forests as often they don't change between Octopus releases.

**Comment by XavierMialhe** [comment]
Thank you for your quick reply !
