### ISSUE TITLE
Any chance of updating the bioconda recipe to 0.6.3-beta?

### ISSUE THREAD

**Issue by tfenne** [luntergroup/octopus#59]
**Describe the bug**
The conda recipe is four versions behind the current release, but is the easiest way to get octopus installed and running along side other bioinformatics tools. Any chance someone could update the recipe, and perhaps add that to the checklist for future releases?

I did start updating the recipe myself, but was a) unsure about specifying some of the new dependencies and b) wasn't entirely sure how to deal with the patch file since that has hardcoded paths that involve the version number.  Sorry.

**Comment by dancooke** [comment]
Thanks for your interest in Octopus. I've been [trying](https://github.com/bioconda/bioconda-recipes/pull/13583) to get the Bioconda version bumped for a while now but there are some issues with the new Bioconda Boost package. I'll ping the Bioconda team another message.

By the way, depending on your system, Octopus can run substantially faster when compiled from source on the target machine compare with the Bioconda version.

**Comment by rspreafico-vir** [comment]
@dancooke I have a PR open with bioconda to build octopus 0.6.3 that worked successfully on Linux, but not on Mac:

https://github.com/bioconda/bioconda-recipes/pull/18935

`boost` seems to be recognized on Mac, the issue now is `htslib`:

```
21:55:56 BIOCONDA INFO (ERR) -- Installation prefix: /Users/distiller/project/miniconda/conda-bld/octopus_1574833993285/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin
21:55:58 BIOCONDA INFO (ERR) HTSlib_INCLUDE_DIR=HTSlib_INCLUDE_DIR-NOTFOUND
21:55:58 BIOCONDA INFO (ERR) HTSlib_LIBRARY=/Users/distiller/project/miniconda/conda-bld/octopus_1574833993285/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/lib/libhts.dylib
21:55:58 BIOCONDA INFO (ERR) CMake Error at build/cmake/modules/FindHTSlib.cmake:67 (message):
21:55:58 BIOCONDA INFO (ERR)   Required library HTSlib NOT FOUND.
21:55:58 BIOCONDA INFO (ERR) 
21:55:58 BIOCONDA INFO (ERR)   Install the library (dev version) and try again.  If the library is already
21:55:58 BIOCONDA INFO (ERR)   installed, use ccmake to set the missing variables manually.
21:55:58 BIOCONDA INFO (ERR) Call Stack (most recent call first):
21:55:58 BIOCONDA INFO (ERR)   build/cmake/modules/FindHTSlib.cmake:144 (libfind_process)
21:55:58 BIOCONDA INFO (ERR)   src/CMakeLists.txt:692 (find_package)
```

Do you have any idea on how to solve this? I will also ping the Bioconda crew.

**Comment by rspreafico-vir** [comment]
Now available!

https://github.com/bioconda/bioconda-recipes/pull/18935

**Comment by dancooke** [comment]
@rspreafico-vir Thanks!
