### ISSUE TITLE
Question: Does octopus support short genome?

### ISSUE THREAD

**Issue by ChuanyiZ** [luntergroup/octopus#63]
I was testing octopus on a toy example with a reference whose size is only 5000bp (taken from the demo in Strelka2). Based on that reference FASTA, I made several cancer samples but octopus doesn't report any somatic variants.

The question is, is this supposed to happen? Is octopus able to run on this kind of small, artificial sample?

The debugging log is attached.
version: v0.6.3-beta
system: CentOS Linux release 7.6.1810
[octopus_debug.log](https://github.com/luntergroup/octopus/files/3164216/octopus_debug.log)

**Comment by dancooke** [comment]
Octopus should have no problem with small contigs. The debug log indicates that no candidate variation was detected. Can you send the BAM files and I'll have a look at what's going on?

**Comment by ChuanyiZ** [comment]
I just found that it is the issue with the input BAM files. Octopus runs perfectly now. Sorry for bothering.

**Comment by dancooke** [comment]
What was the issue? Perhaps I can make Octopus emit a warning in the future.

**Comment by ChuanyiZ** [comment]
I wrote a bash script to generate BAM files, add variants into BAM files and run octopus. There's a wrong filename that makes the input BAM files contain no variants. I think it's reasonable for octopus to generate a VCF with no variants in this case.
