### ISSUE TITLE
Config file handling of --kmer-sizes broken

### ISSUE THREAD

**Issue by iamh2o** [luntergroup/octopus#64]
**Describe the bug**
When using a config file with octopus, I can not seem to get the 'kmer-sizes' option to work as it does on the command line with --kmer-sizes.
`[2019-05-12 18:56:23] <INFO> ------------------------------------------------------------------------
[2019-05-12 18:56:23] <INFO> octopus v0.6.3-beta (HEAD fd981298)
[2019-05-12 18:56:23] <INFO> Copyright (c) 2015-2019 University of Oxford
[2019-05-12 18:56:23] <INFO> ------------------------------------------------------------------------
[2019-05-12 18:56:23] <EROR> A user error has occurred:
[2019-05-12 18:56:23] <EROR> 
[2019-05-12 18:56:23] <EROR>     The argument ('10 15 20') for option 'kmer-sizes' is invalid.
[2019-05-12 18:56:23] <EROR> 
[2019-05-12 18:56:23] <EROR> To help resolve this error use the --help command to view required and
[2019-05-12 18:56:23] <EROR> allowable options.
[2019-05-12 18:56:23] <INFO> ------------------------------------------------------------------------
`
the cfg file looks like:
"""kmer-sizes=10 15 20""", I tried the following as well:
"""kmer-sizes='10 15 20'"""
"""kmer-sizes=10,15,20"""

all fail the same way.  However, when I only specify one value:
"""kmer-sizes=10""", it works!

on the command line, this works (as the user manual suggests is the default:
"""--kmer-sizes 10 15 20 """

I can work around this for now, but i would much rather have everything in a config file :-)

And while I'm at it, a new feature request I'd love to see is some kind of logging of the params set in the config file (in cases the file goes missing or is over-written.  

**Command**
Command line to run octopus:
```shell
octopus --reference /mnt/disks/data5/data/reference/human/hs38DH/hs38DH.fa         --reads NA12878.aligned.deduped.sort.bam         -t regions.bed         --forest-file /mnt/disks/data5/data/reference/human/germline.v0.6.3-beta.forest         -o NA12878.octopus.vcf.gz         --threads 900         -X 2000MB         -B 50GB         --config ./octopus.cfg         --annotations AD ADP AF ARF BQ CRF DP FRF GC GQ MC MF MQ MQ0 QD QUAL SB STR_LENGTH STR_PERIOD  &> logs/octopus.NA12878.log```

**Desktop (please complete the following information):**
 - AWS, large core&mem machine

**Additional context**
n/a

**Comment by dancooke** [comment]
Thanks for the feedback. One way around this limitation while still using config files is to put each value on a separate line:

    kmer-sizes=10
    kmer-sizes=15
    kmer-sizes=20

I'll try to have the single-line variant working in the next release. I'll also look at logging the config file parameters.

**Comment by dancooke** [comment]
Logging of all command line options added in 4be45ab0079d7847f47e3e8bca021542f4180f0e.

**Comment by dancooke** [comment]
I'm going to close this since I'm satisfied with the way multi-argument options are handled (as [shown](https://github.com/luntergroup/octopus/issues/64#issuecomment-491708830)).
