### ISSUE TITLE
Profiler Script Failing w/Pandas Error

### ISSUE THREAD

**Issue by iamh2o** [luntergroup/octopus#67]
**Describe the bug**
I am running the ./profile.py script.  It churns for about 1min, then dumps a padas error.

**Command**
Command line to run octopus:
```
~/octopus/scripts/profiler.py -P ./NA24385.octops.eror.profile -O ./Invitae_error_profile
```

**Desktop (please complete the following information):**
 - OS:  ass 96 core big mem instance
 - Version v0.6.3-beta
 - Reference [e.g. hg19] hg38

**Additional context**
Here is the error message:
`(wgspy3) ubuntu@ai-parabricks:/mnt/disks/data5/results/OCT_TESTS/new_err_model/NA24385$ ~/octopus/scripts/profiler.py -P ./NA24385.octops.eror.profile -O ./Invitae_error_profile
Traceback (most recent call last):
  File "/home/ubuntu/octopus/scripts/profiler.py", line 154, in <module>
    main(parsed)
  File "/home/ubuntu/octopus/scripts/profiler.py", line 139, in main
    profiles_df = read_indel_error_profile_and_summary(options.profile)
  File "/home/ubuntu/octopus/scripts/profiler.py", line 60, in read_indel_error_profile_and_summary
    return read_indel_error_profile_summaries(read_indel_profile(csv))
  File "/home/ubuntu/octopus/scripts/profiler.py", line 57, in read_indel_error_profile_summaries
    return make_error_summaries(indel_profile_df)
  File "/home/ubuntu/octopus/scripts/profiler.py", line 48, in make_error_summaries
    result['period'] = aggregate_errors(indel_profile_df)
  File "/home/ubuntu/octopus/scripts/profiler.py", line 25, in aggregate_errors
    errors_df = errors_df.groupby(aggregators).aggregate(aggregation_functions, axis='columns')
  File "/home/ubuntu/conda/envs/wgspy3/lib/python3.7/site-packages/pandas/core/generic.py", line 7632, in groupby
    observed=observed, **kwargs)
  File "/home/ubuntu/conda/envs/wgspy3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 2110, in groupby
    return klass(obj, by, **kwds)
  File "/home/ubuntu/conda/envs/wgspy3/lib/python3.7/site-packages/pandas/core/groupby/groupby.py", line 360, in __init__
    mutated=self.mutated)
  File "/home/ubuntu/conda/envs/wgspy3/lib/python3.7/site-packages/pandas/core/groupby/grouper.py", line 572, in _get_grouper
    obj._check_label_or_level_ambiguity(gpr)
  File "/home/ubuntu/conda/envs/wgspy3/lib/python3.7/site-packages/pandas/core/generic.py", line 1655, in _check_label_or_level_ambiguity
    raise ValueError(msg)
ValueError: 'period' is both an index level and a column label, which is ambiguous.
`

And the head of my profile data
`period,periods,motif,reference_count,reference_span,indel_length,polymorphisms,errors,reads
0,0,N,1,1246006805,1,104790,1152591,311952597
0,0,N,1,1246006805,2,34357,466076,311952597
0,0,N,1,1246006805,3,10783,283051,311952597
0,0,N,1,1246006805,4,14604,195937,311952597
0,0,N,1,1246006805,5,3877,188535,311952597
0,0,N,1,1246006805,6,4558,167425,311952597
0,0,N,1,1246006805,7,1496,198103,311952597
0,0,N,1,1246006805,8,3374,126899,311952597
0,0,N,1,1246006805,9,1069,225,311952597
0,0,N,1,1246006805,10,1957,189,311952597
0,0,N,1,1246006805,11,678,122,311952597
0,0,N,1,1246006805,12,1655,91,311952597
0,0,N,1,1246006805,13,487,54,311952597
0,0,N,1,1246006805,14,877,40,311952597
0,0,N,1,1246006805,15,498,18,311952597
0,0,N,1,1246006805,16,776,0,311952597
0,0,N,1,1246006805,17,267,0,311952597
0,0,N,1,1246006805,18,486,0,311952597
0,0,N,1,1246006805,19,223,0,311952597
0,0,N,1,1246006805,20,463,0,311952597
0,0,N,1,1246006805,21,148,0,311952597
`

**Comment by dancooke** [comment]
Which commit are you building (i.e. output from `octopus --version`)? This looks like the same problem as in issue #65 which [I believe was fixed](https://github.com/luntergroup/octopus/issues/65#issuecomment-495135004) in 4d3a1951c035eb0a17b1da9349a933dd0566b31b.

**Comment by iamh2o** [comment]
What version of numpy and pandas are you using? This seems like a thing that used to be allowed but recently became an exception.  I took a stab at updating the script, but failed to get it working (and was worried I would not be aware of unexpected negative consequences even if it did run).  If i can run using your numpy env, that could get me around the problem fastest.

**Comment by iamh2o** [comment]
(wgspy3) ubuntu@ai-parabricks:~$ octopus --version
octopus version 0.6.3-beta (HEAD fd981298)
Target: x86_64 Linux 4.4.0-1075-aws
Compiler: GNU 7.4.0
Boost: 1_67

**Comment by iamh2o** [comment]
I'm giving the new version a shot now.

**Comment by iamh2o** [comment]
That indeed fixed it!  This can be closed :-)

and just to confirm, the usage now would be --sequence-error-model /path/to/model/file 
and --sequence-error-model PCR-free.NOVASEQ is no longer needed?

**Comment by dancooke** [comment]
Great. Yes that's correct. I'll be very interested to know how your results change with the new error model!
