### ISSUE TITLE
Problems with ' $ python3 ./test/install.py'

### ISSUE THREAD

**Issue by Tcvalenzuela** [luntergroup/octopus#69]
Dear all

I'm having problems with my installation of octopus.

I installed through conda  $ conda install octopus

and trying to do $ python3 ./test/install.py  I get:

$ python3 ./test/install.py 
-- Build type: Release
-- Installation prefix: /home/tomas/programs/octopus/bin
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
--   date_time
--   log_setup
--   log
--   iostreams
--   timer
--   thread
--   regex
--   chrono
--   atomic
-- Boost include dir: /usr/include
-- Boost libraries: /usr/lib/x86_64-linux-gnu/libboost_system.so/usr/lib/x86_64-linux-gnu/libboost_filesystem.so/usr/lib/x86_64-linux-gnu/libboost_program_options.so/usr/lib/x86_64-linux-gnu/libboost_date_time.so/usr/lib/x86_64-linux-gnu/libboost_log_setup.so/usr/lib/x86_64-linux-gnu/libboost_log.so/usr/lib/x86_64-linux-gnu/libboost_iostreams.so/usr/lib/x86_64-linux-gnu/libboost_timer.so/usr/lib/x86_64-linux-gnu/libboost_thread.so-pthread/usr/lib/x86_64-linux-gnu/libboost_regex.so/usr/lib/x86_64-linux-gnu/libboost_chrono.so/usr/lib/x86_64-linux-gnu/libboost_atomic.so
-- GMP_INCLUDES=/usr/include/x86_64-linux-gnu
-- Found HTSlib 
--    HTSlib include dirs: /usr/local/include
--    HTSlib libraries: /usr/local/lib/libhts.so
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
-- Generating done
-- Build files have been written to: /home/tomas/programs/octopus/build
[  1%] Built target libdivsufsort
[  2%] Built target tandem
[  8%] Built target ranger
[  8%] Linking CXX shared library libOctopus.so
/usr/bin/ld: ../lib/ranger/libranger.a(Forest.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN6ranger6ForestE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/CMakeFiles/Octopus.dir/build.make:3297: recipe for target 'src/libOctopus.so' failed
make[2]: *** [src/libOctopus.so] Error 1
CMakeFiles/Makefile2:280: recipe for target 'src/CMakeFiles/Octopus.dir/all' failed
make[1]: *** [src/CMakeFiles/Octopus.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

Do you have any ideas of what can be wrong

**Comment by dancooke** [comment]
I don't know if the Bioconda package is set up to be able to install and run the tests - I don't actively maintain it. There's little point in running the tests as a user in any case; they are primarily for development purposes.
