### ISSUE TITLE
installation test requires boost 1.61 not boost 1.58

### ISSUE THREAD

**Issue by AKWB** [luntergroup/octopus#7]
Hi,

I would like to try Octopus. Installation seems to be so far ok, but the testing did not work:
test/install.py

--> required boost version 1.61 (1.58 is installed and the latest version to get via apt)
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   system
--   filesystem
--   program_options
--   date_time
--   log_setup
--   log
--   iostreams
--   timer
--   thread
--   regex
--   chrono
--   atomic
-- Found HTSlib 
--    HTSlib include dirs: /usr/local/include/htslib;/usr/include
--    HTSlib libraries: /usr/local/lib/libhts.so;/usr/lib/x86_64-linux-gnu/libz.so
CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Detected version of Boost is too old.  Requested version was 1.61 (or
  newer).
Call Stack (most recent call first):
  test/unit/CMakeLists.txt:61 (find_package)

-- Configuring incomplete, errors occurred!
See also "/usr/local/octopus/build/CMakeFiles/CMakeOutput.log".
See also "/usr/local/octopus/build/CMakeFiles/CMakeError.log".

Greets,
Anke

**Comment by dancooke** [comment]
Hi Anke,

I forgot to downgrade the Boost requirement in the unit test CMake file from 1.61 to 1.58. I'll make sure this is changed in the next patch. Just so you know, building the unit tests is not a requirement to using octopus; they are just a development tool.

BW
Dan

**Comment by dancooke** [comment]
I've downgraded the Boost requirement to 1.58 in the develop branch, it will be included in the next release.
