### ISSUE TITLE
Downloading forest germline variant

### ISSUE THREAD

**Issue by 24natasya** [luntergroup/octopus#73]
Hi ! 

I am trying to run the random forest filtering but the file is unable to be downloaded to the directory file which gives me this error: Failed to download forest germline.v0.6.3-beta.forest. 
I had already set a google cloud account but it gives me this error: The billing account for project 437709507887 is disabled in state closed. 

How to resolve this?

**Comment by dancooke** [comment]
I think this may have been due to a problem with our Google Cloud account. Can you please try again and report back?

**Comment by 24natasya** [comment]
Sure i will try it again

**Comment by 24natasya** [comment]
> I think this may have been due to a problem with our Google Cloud account. Can you please try again and report back?

It works now! Thanks
