### ISSUE TITLE
How to interpret `*` with extra bases as an ALT allele

### ISSUE THREAD

**Issue by tfenne** [luntergroup/octopus#75]
I'm looking at some calls generated by octopus without the `--legacy` option, found some surprising (to me) ALT alleles that are composed of a `*` followed by one or more bases.  The following is an example, starting from the beginning of a phase set through to a variant with such an allele:

```
chr1  1157219  .  G                      C                      689.92  PASS  <snip>  GT:GQ:DP:MQ:PS:PQ:AD:ADP:AF:ARF:BQ:FRF:MC:MF:SB:RFQUAL:FT  1|0:683:62:60:1157219:99:30:64:0.469:0.000:37:0.031:0:0.000:0.065:5.25:PASS
chr1  1157285  .  CCCCGCCCCCAGCCCACCCAT  C                      356.5   PASS  <snip>  GT:GQ:DP:MQ:PS:PQ:AD:ADP:AF:ARF:BQ:FRF:MC:MF:SB:RFQUAL:FT  1|0:357:45:60:1157219:99:22:49:0.449:0.093:.:0.167:13:0.241:0.068:4.96:PASS
chr1  1157335  .  GCCCACCCATC            G                      289.21  PASS  <snip>  GT:GQ:DP:MQ:PS:PQ:AD:ADP:AF:ARF:BQ:FRF:MC:MF:SB:RFQUAL:FT  1|0:289:29:60:1157219:99:14:37:0.378:0.032:.:0.065:8:0.258:0.201:4.68:PASS
chr1  1157345  .  CCCATCCCCGCCATCCCCG    C,*CCATCCCCGCCATCCCCG  252.62  PASS  <snip>  GT:GQ:DP:MQ:PS:PQ:AD:ADP:AF:ARF:BQ:FRF:MC:MF:SB:RFQUAL:FT  2|1:99:29:60:1157219:99:16:75:0.213:0.029:37:0.171:7:0.200:0.155:5.57:PASS
```

I can't find anything in the user documentation that would lead me to expect alleles like this.  I _think_ the correct interpretation of the allele in this case is that the first base is deleted by an upstream deletion, and but the remaining bases from the REF allele are not deleted by the upstream deletion.  Is that correct?  

What's the expected representation if e.g. 2 bases are covered by an upstream deletion and then the REF allele continues?  I can't find any examples of `**` followed by bases nor of `*` followed by fewer than len(REF)-1 bases, so I'm not sure what to expect in that situation.

**Comment by dancooke** [comment]
Your interpretation is correct. The `*` allele is valid VCF and is documented [here](https://github.com/luntergroup/octopus/wiki/VCF-format#overlapping-sites), although 'partial' spanning deletions like in your example are not currently documented, and the VCF specification is currently ambiguous on them (see [this discussion](https://github.com/samtools/hts-specs/issues/151#issuecomment-447180875)).

If the first two bases of a `REF` allele with length > 2 bases are overlapped with an upstream deletion, then you should indeed see `**` followed by remaining reference bases. I would expect this situation to be rare however as the vast majority of overlapping deletions occur in tandem repeats, with the most common case being a shared anchor base after left alignment, resulting in the standard `*`-only `ALT` allele. The rarer case resulting in partial overlapping deletions like in your example predominantly occurs with two distinct adjacent tandem repeats.

The other use of `*` that is not currently documented is when an allele overlaps with a complex replacement. In this situation you will also get multiple `*`s, such as:

```shell
2	169691013	.	GCGCGCACA	ACACACACACACACACGCG	285.14	PASS	AC=1;AN=1;DP=42;MQ=59;MQ0=0;NS=1	GT:GQ:DP:MQ:PS:PQ:RFQUAL:FT	1|.:213:42:59:169691013:99:14.55:PASS
2	169691017	.	GCA	G,***	212.7	PASS	AC=2;AN=2;DP=41;MQ=59;MQ0=0;NS=1	GT:GQ:DP:MQ:PS:PQ:RFQUAL:FT	2|1:213:41:59:169691013:99:7.93:PASS
```

and

```shell
6	62655007	.	AAAAAAAAAAAG	TATATATATATATATGTA	1392.24	PASS	AC=1;AN=1;DP=57;MQ=57;MQ0=0;NS=1	GT:GQ:DP:MQ:PS:PQ:RFQUAL:FT	.|1:424:57:57:62655007:99:9.28:PASS
6	62655015	.	AAAGTATATATAT	A,****TATATATAT	424.07	PASS	AC=2;AN=2;DP=57;MQ=57;MQ0=0;NS=1	GT:GQ:DP:MQ:PS:PQ:RFQUAL:FT	1|2:424:57:57:62655007:99:10.31:PASS
```

The intention is to show that the bases are non-reference, but have already been explained by a previous record.

**Comment by dancooke** [comment]
Closing as discussion moved to [hts-specs](https://github.com/samtools/hts-specs/issues/437).
