### ISSUE TITLE
I have true sets, which vardict call high FP in tumor-only

### ISSUE THREAD

**Issue by wentgithub** [luntergroup/octopus#76]
thanks for making this software calling the complex variant, this super all others.

but I found another problem, for tumor-only, even for paired, has high FP.
these days I also test a paired standard sample.

you know like gatk, it can supply a germline resource to filter gemline vatrianrts, can vardict also use this?

**Comment by dancooke** [comment]
You seem to be referring to problems with another tool - VarDict?

**Comment by wentgithub** [comment]
sorry for making such mistake.

**Comment by dancooke** [comment]
No problem. So can I close this issue or did you mean to say you're experiencing this issue with Octopus?

**Comment by wentgithub** [comment]
wait for a moment, can your tool call complex variant like varidict? thanks a lot

**Comment by dancooke** [comment]
Yes. Please see the [README](https://github.com/luntergroup/octopus), [wiki](https://github.com/luntergroup/octopus/wiki), and [pre-print](https://www.biorxiv.org/content/early/2018/10/29/456103).

**Comment by dancooke** [comment]
Closing as not an issue with Octopus. FYI, you might want to refer to [this issue](https://github.com/AstraZeneca-NGS/VarDict/issues/68).
