### ISSUE TITLE
how the software distinguish gemline or somatic in one sample mode

### ISSUE THREAD

**Issue by wentgithub** [luntergroup/octopus#77]
thanksa for this useful software.
after readoing this. I have some puzzles.
because the somatic examples does not give tumor-only mode, just give this

> If a normal sample is not present the cancer calling model must be invoked explicitly:
> $ octopus -R hs37d5.fa -I tumour1.bam tumour2.bam

so I guess tumor-only mode will be octopus -R hs37d5.fa -I tumour1.bam  -C cancer, am I right, if not so , the command will the same with gemline calling.

> Calling germline variants in an individual
> This is the simplest case, if the file NA12878.bam contains a single sample, octopus will default to its individual calling model:
> 
> $ octopus --reference hs37d5.fa --reads NA12878.bam

for indel, will this caller report the variant to 3` if the reference is repeat sequence, like gatk vardict , they just report 5`, which is not compatible with hgvs

thanks a lot

**Comment by dancooke** [comment]
Like the documentation states

```shell
$ octopus --reference hs37d5.fa --reads NA12878.bam
```

invokes the [individual](https://github.com/luntergroup/octopus/wiki/Calling-models:-Individual) calling model, and is equivalent to

```shell
$ octopus -C individual --reference hs37d5.fa --reads NA12878.bam
```

If you want tumour-only calling then you must explicitly specify the [cancer](https://github.com/luntergroup/octopus/wiki/Calling-models:-Cancer) calling model

```shell
$ octopus -C cancer --reference hs37d5.fa --reads tumour.bam
```

> for indel, will this caller report the variant to 3 if the reference is repeat sequence, like gatk vardict , they just report 5, which is not compatible with hgvs

Sorry, I don't understand your question. Can you try to rephrase or give an example?

**Comment by wentgithub** [comment]
chr20	31022441	.	AG	A,AGG	.	multiallelic;slippage	CONTQ=93;DP=2328;ECNT=1;GERMQ=93;MBQ=35,35,35;MFRL=227,223,225;MMQ=60,60,60;MPOS=23,26;NALOD=-3.052e+01,-1.097e-01;NLOD=204.18,268.64;POPAF=6.00,6.00;ROQ=93;RPA=8,7,9;RU=G;SEQQ=93;STR;STRANDQ=93;STRQ=1;TLOD=16.80,603.60	GT:AD:AF:DP:F1R2:F2R1:SB	0/1/2:691,21,322:0.018,0.308:1034:352,11,159:313,10,152:341,350,151,192	0/0:937,31,9:0.030,6.233e-03:977:469,17,2:435,14,7:456,481,19,21
<br>
![image](https://user-images.githubusercontent.com/48668142/63636631-5b49a500-c6a4-11e9-8f33-9d7acbfa3e99.png)
<br>
but the hgvs need you give the last G not the first G

> chr20 31022449 - - G ASXL1 INS NM_015338 c.1934dupG p.Gly646Trpfs

**Comment by dancooke** [comment]
Most variant callers, including Octopus, will report output in [VCF](https://samtools.github.io/hts-specs/VCFv4.3.pdf) that specifies that reference anchor bases must be 5' of the indel event being reported. If you want another format then you'll need to find a conversion tool or write your own.

**Comment by wentgithub** [comment]
why the tool can not report 3` , is there any reason, thanks a lot

**Comment by dancooke** [comment]
Like I said, the VCF specification requires indel anchor bases be 5' of the indel event, not 3'. I don't know the reason for this decision - if that's what you're asking. Maybe you should ask the [hts-spec](https://github.com/samtools/hts-specs) people.

**Comment by wentgithub** [comment]
thanks a lot
