### ISSUE TITLE
Converting CSV file from classified calls 

### ISSUE THREAD

**Issue by 24natasya** [luntergroup/octopus#82]
Hi ! I am training forest but I am unable to convert the CSV file from the classified calls csv. Can you provide a detail example to convert the csv file?

**Comment by dancooke** [comment]
Have you tried using the bundled [Python script](https://github.com/luntergroup/octopus/blob/develop/scripts/train_random_forest.py)? If you provide details of your training data then I can advise how to use the script.

**Comment by 24natasya** [comment]
Hi, yes appreciate if you could advise me on that. I am currently doing
training on sample : NA12878 for germline analysis.

my reference fasta is : hs37d5
Im using truth set from GIAB (NA12878)
HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_nosomaticdel.bed
HG001_GRCh37_GIAB_highconf_CG-IllFB-IllGATKHC-Ion-10X-SOLID_CHROM1-X_v.3.3.2_highconf_PGandRTGphasetransfer.vcf.gz
GRCh37_nexterarapidcapture_expandedexome_targetedregions.bed

**Comment by dancooke** [comment]
Ok, and what is your input read data, just a single BAM file?

**Comment by 24natasya** [comment]
Yes just a single BAM file

**Comment by dancooke** [comment]
Closing as this is already documented.
