### ISSUE TITLE
Arguments for data-profile

### ISSUE THREAD

**Issue by 24natasya** [luntergroup/octopus#85]
I just want to ask, what arguments to i specify for --data-profile . Does is requires a vcf files or a truth file?

**Comment by dancooke** [comment]
The argument is a (CSV) file path where Octopus will write the data profile to, e.g.:

```shell
$ octopus -R ref.fa -I reads.bam -o calls.vcf --data-profile reads.profile.csv
```

You then use one or more profiles to generate new [error models](https://github.com/luntergroup/octopus/wiki/How-to:-Use-error-models):

```shell
$ profiler.py -P reads.profile.csv -O reads.model
```

Then you can use this error model for variant calling:

```shell
$ octopus -R ref.fa -I reads.bam -o calls.vcf --sequence-error-model reads.model
```

There is no truth set needs to fit the error model.

**Comment by 24natasya** [comment]
Thanks for your prompt reply. I really appreciate!

**Comment by brentp** [comment]
@dancooke , one clarification on this, do the other arguments to octopus matter? E.g. if the data is from haploid clones, would the  `-C polyclone` and other appropriate arguments matter?
