### ISSUE TITLE
How to annotate the resulting VCF?

### ISSUE THREAD

**Issue by jlee110** [luntergroup/octopus#98]
Hello,

I keep getting errors from trying to annotate the called variants using Variant Effect Predictor. Is octopus incompatible with VEP? I used "--legacy" and octopus_to_rtg.py to get the somatics only.

Error:
Can't call method "isa" on an undefined value at /nfs/public/release/ensweb/latest/live/www/www_98/ensembl/modules/Bio/EnsEMBL/TopLevelAssemblyMapper.pm line 223, <__ANONIO__> line 22970.

Thank you
Jay

**Comment by dancooke** [comment]
Can you provide a sample VCF that's failing?

**Comment by jlee110** [comment]
[3642_B5_Tum_DNA_legacy.legacy.somatic.vcf.zip](https://github.com/luntergroup/octopus/files/3947426/3642_B5_Tum_DNA_legacy.legacy.somatic.vcf.zip)

**Comment by dancooke** [comment]
The record that's failing is

```
KI270746.1	40540	.	G	GT	103.02	FRF	AC=1;AN=3;DP=26;MQ=49;MQ0=0;NS=1;PP=7.41;SOMATIC	GT:GQ:DP:MQ:PS:PQ:MAP_VAF:VAF_CR:FT	0/1:89:26:49:40540:99:0.42:0.27,0.58:FRF
```

Even if I simplify this to

```
KI270746.1	40540	.	G	GT	50	.	.
```

It still fails, which would indicate that this is a problem with VEP, not Octopus.
